### ISSUE TITLE
Left title overlaps current title with long text during right dragging

### ISSUE THREAD

**Issue by alecava** [JakeWharton/ViewPagerIndicator#101]
Hi, I found out that when I have long title texts in the indicator, during right dragging, the title in the left part of the indicator overlaps the current title until the motion is over. 

This behavior doesn't happen when I scroll in the opposite direction.

An example of this behavior can be found here => http://dl.dropbox.com/u/1146701/view-page-indicator-overlaps.png

**Comment by alecava** [comment]
I resolved the bug by myself adding this block of code:

if (i < boundsSize - 1)
 {
     Rect rightBound = bounds.get(i + 1);
     //Intersection
     if (bound.right + mTitlePadding > rightBound.left) {
         int w = bound.right - bound.left;
         bound.left = (int) (rightBound.left - w - mTitlePadding);
         bound.right = bound.left + w;
     }
}

after line 432

**Comment by mttkay** [comment]
I've seen this happening, too. @alecava do you wanna create a pull request for this perhaps? I would say that makes it more likely for a fix to go in... just saying.

**Comment by alecava** [comment]
Yes, you're right, i'm going to try
