### ISSUE TITLE
Maven build fails on a fresh checkout

### ISSUE THREAD

**Issue by mttkay** [JakeWharton/ViewPagerIndicator#102]
After cloning the repo, you cannot build the project with Maven, since a dependency is missing (it's not on Central, and doesn't seem to be part of the library itself. The missing component is directionalviewpager:library:jar. The error is:

[INFO] Reactor Summary:
[INFO] 
[INFO] Android-ViewPagerIndicator (Parent) ............... SUCCESS [2.525s]
[INFO] Android-ViewPagerIndicator ........................ SUCCESS [5.764s]
[INFO] Android-ViewPagerIndicator Sample ................. FAILURE [0.304s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 9.621s
[INFO] Finished at: Thu Jun 21 16:13:57 CEST 2012
[INFO] Final Memory: 20M/81M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project sample: Could not resolve dependencies for project com.viewpagerindicator:sample:apk:2.3.1: Could not find artifact com.directionalviewpager:library:jar:1.2.0 in central (http://repo1.maven.org/maven2) -> [Help 1]

**Comment by JakeWharton** [comment]
Fixed by d94643b36bf35898c7fc3aac8eab66ffb7911a39 on `dev` branch.
