### ISSUE TITLE
Compatibility library is shipped as a JAR, clashes with app dependencies

### ISSUE THREAD

**Issue by mttkay** [JakeWharton/ViewPagerIndicator#103]
The library project comes with the Android support-v4 library in lib/. That's a problem whenever the app using ViewPagerIndicator depends on the support library too, since that will make the dexer fail with duplicate class errors.

I noticed the POM defines the support lib as provided; why? That should be "compile". It's a compile time dependency and is never provided, as it must always be shipped with an app. The provided scope is meant for platform JARs.

**Comment by JakeWharton** [comment]
It was listed as `provided` since ABS used to replace the support library altogether and I was using both in an app. Now that they both use them as regular dependencies this can be switched.
