### ISSUE TITLE
Current position of my CirclePagedIndicator

### ISSUE THREAD

**Issue by temonteiro** [JakeWharton/ViewPagerIndicator#107]
Hi,
Do not know if this is right place to ask questions, but I'm desperate! <õ>
I need to recover the position of CirclePagedIndicator that the user is currently viewing, is this possible?

PS.: Sorry for the english :)

**Comment by JakeWharton** [comment]
[Ask the `ViewPager`](http://developer.android.com/reference/android/support/v4/view/ViewPager.html#getCurrentItem%28%29)
