### ISSUE TITLE
LazyList on CirclePageIndicator

### ISSUE THREAD

**Issue by temonteiro** [JakeWharton/ViewPagerIndicator#109]
Good morning,
I had a problem "java.lang.IllegalStateException: get field slot from row 0 col 0 failed" due to my cursor to bring a file larger than 1MB.
I wonder if you can use to build the LazyList CirclePageIndicator? If there is another way to bring fewer files when viewing?

**Comment by JakeWharton** [comment]
CirclePageIndicator doesn't throw IllegalStateExceptions anywhere. I have a feeling this is caused by whatever you are placing inside the ViewPager.

**Comment by karthikrao19** [comment]
how to set drawable to CirclePageIndicator. I used IconPageIndicator lib but onclick method is not working here.
