### ISSUE TITLE
Changing Dataset Not Updating Titles

### ISSUE THREAD

**Issue by JakeWharton** [JakeWharton/ViewPagerIndicator#11]
Adding a page to the bound adapter and calling `notifyDataSetChanged()` will properly notify the `ViewPager` but a `TitlePageIndicator` widget will not update. This should be due to not acting on the `onPageSelected` callback for the listener. However, ignoring this callback was a deliberate design decision--the reason for which unfortunately now escapes me.

**Comment by JakeWharton** [comment]
I'm 99.9% sure this cannot be done. I'm adding a `notifyDataSetChanged()` method to the indicators but all it does is call `invalidate()`. So you'll have to notify both the adapter and the indicator if your data set (or even just the titles) change to trigger a full redraw.

**Comment by SimonVT** [comment]
Just invalidating the view is not enough. If you are at the last page and remove it from the adapter, invalidating the view will cause an index out of bounds in onDraw.
I suggest saving the position from onPageSelected in a variable, then after notifyDataSetChanged is called on the adapter, move it to mCurrentPage and invalidate the view.
