### ISSUE TITLE
Adding icons to TitlePageIndicator

### ISSUE THREAD

**Issue by scompt** [JakeWharton/ViewPagerIndicator#115]
I'm about to start adding support for icons to `TitlePageIndicator`. They'll look similar to the icons that are available if you use ActionBar tabs. I'd like to get the feature merged into VPI. Is there anything in particular that it should be able to do? I'm planning on creating an `IconProvider` interface analogous to the now-gone `TitleProvider`.

**Comment by scompt** [comment]
I've pushed a first attempt at this to [my fork](https://github.com/scompt/Android-ViewPagerIndicator/tree/features/title_icons). I know the spacing of the icon isn't yet correct, but I'd welcome some initial feedback.

**Comment by JakeWharton** [comment]
I'd rather move to using `TextView`s for the title indicator before adding support for something like this. If each title was a `TextView` then adding a compound drawable is easy.

**Comment by scompt** [comment]
I totally agree. Switching to `TextView`s would be a much cleaner and easier implementation.

That'll probably be a larger project. In the meantime, I'll be maintaining my branch for the app I'm developing. If you don' think it'll get merged, feel free to close this issue.

**Comment by JakeWharton** [comment]
Closing as I added it as a requirement to the `TextView`-based rewrite issue.
