### ISSUE TITLE
Background is not set

### ISSUE THREAD

**Issue by SanderTuit** [JakeWharton/ViewPagerIndicator#117]
When I create a custom style and set the android:background attribute in a style for vpiTitlePageIndicatorStyle, it isn't used. The background remains the default colour. When I set the text colour for the TitlePageIndicator I'm using in the same style, this does work.

**Comment by ChrisDavis8** [comment]
You seem to have used CirclePageIndicator_android_background in LinePageIndicator, TitlePageIndicator and UnderlinePageIndicator

**Comment by brk3** [comment]
@ChrisDavis8 Correct, seems to be fixed on the dev branch.
