### ISSUE TITLE
Styling that works with Titles doesn't work with Tabs.

### ISSUE THREAD

**Issue by Michael-Zinn** [JakeWharton/ViewPagerIndicator#120]
Styling TitlePageIndicators by methods works flawlessly, but it doesn't work for TabPageIndicators, since the methods are missing. Basically, I want to do this during runtime, but the methods are only available in TitlePageIndicators:

<pre>
TabPageIndicator indicator = (TabPageIndicator) findViewById(R.id.mainindicator);
indicator.setViewPager(pager);

indicator.setBackgroundColor(design.getBar3().background.getARGB());
indicator.setScrollBarStyle(indicator.STATUS_BAR_VISIBLE);
indicator.setFooterIndicatorStyle(IndicatorStyle.None);
indicator.setFooterLineHeight(1 * density);
        
// marker
indicator.setFooterColor(design.getBar1().background.getARGB());
indicator.setFooterLineHeight(1 * density); // 1dp
indicator.setFooterIndicatorHeight(3 * density); // 3dp
indicator.setFooterIndicatorStyle(IndicatorStyle.Underline);
        
//
indicator.setTextColor(design.getBar3().foreground.getARGB() & 0x00FFFFFF | 0xB0000000);
indicator.setSelectedColor(design.getBar3().foreground.getARGB());
indicator.setSelectedBold(true);
</pre>

**Comment by JakeWharton** [comment]
Tab indicators are actual UI widgets rather than being drawn on a canvas. Because of this, they require proper Android styles to theme.

**Comment by Michael-Zinn** [comment]
Just to clarify, it's not possible to style the titlepager dynamically? It has to be an xml style that existed on compile time? :/

**Comment by JakeWharton** [comment]
The tab pager only. Every other indicator can be dynamically styled with methods.
