### ISSUE TITLE
LinePageIndicator is not clickable

### ISSUE THREAD

**Issue by lexer** [JakeWharton/ViewPagerIndicator#121]
LinePageIndicator doesn't react to user clicks. Is that normal behavior?

**Comment by JakeWharton** [comment]
It has the exact same touch input event handling as other canvas-based indicators. Are you sure you can't click it? Set its height to 50dp or something to confirm.

**Comment by lexer** [comment]
I've increased height. It seems work, but it goes to the next instead of selecting certain page. Is that correct?

**Comment by JakeWharton** [comment]
Yes, it's meant as an indicator and not a navigation device. The left 1/3rd of the control will page left and the right 1/3rd of the control will page right. Clicking in the middle doesn't do anything for this indicator.

**Comment by lexer** [comment]
Ok, Thank you for clarifying details
