### ISSUE TITLE
ViewPagerIndicator causes exceptions when reusing same viewpager with new adapter

### ISSUE THREAD

**Issue by ai212983** [JakeWharton/ViewPagerIndicator#124]
setViewPager method:

```
@Override
public void setViewPager(ViewPager view) {
    if (mViewPager == view) {
        return;
    }
    if (mViewPager != null) {
        mViewPager.setOnPageChangeListener(null);
    }
    mPagerAdapter = view.getAdapter();
    if (mPagerAdapter == null) {
        throw new IllegalStateException("ViewPager does not have adapter instance.");
    }
    mViewPager = view;
    mViewPager.setOnPageChangeListener(this);
    invalidate();
}
```

If I'm using new adapter with same viewpager, viewpagerindicator will ignore that, causing exceptions. My suggestion is just to put pageradapter assignment before (mViewPager == view) check.

**Comment by JakeWharton** [comment]
Fairly certain this is fixed on `dev`. We no longer cache the adapter inside the indicator but rather always rely on the `ViewPager` instance's `getAdapter()` method as the source of truth.

**Comment by warm200** [comment]
what's the dev.
