### ISSUE TITLE
How to add library to maven project

### ISSUE THREAD

**Issue by FlorinDob** [JakeWharton/ViewPagerIndicator#127]
I download the library , add to eclipse(Spring tools) , add to my project pom.xml

``` xml
<dependency>
  <groupId>com.viewpagerindicator</groupId>
  <artifactId>library</artifactId>
  <version>2.3.1</version>
  <type>apklib</type>
</dependency>
```

When i wan`t to import on my project she give me error : The import com.viewpagerindicator cannot be resolved. 
On maven dependency doesn't appear viewpageridicator library!
Thanks in advice !

**Comment by JakeWharton** [comment]
You also need to have the `android-maven-plugin` as a plugin with `<extensions>true</extensions>` specified. If you have setup questions StackOverflow is usually the best place.
