### ISSUE TITLE
Styled/Themed underline page indicator in non functional

### ISSUE THREAD

**Issue by akshaydashrath** [JakeWharton/ViewPagerIndicator#133]
If you style or theme the underline indicator through layout or theme, the first indicator item fills the entire page. The issue exists on the demos as well.

Screenshot: https://docs.google.com/open?id=0B4UIKIiIblQrb3FmSmViWWxtWlE

![](http://i.imgur.com/H7EUF.png)

**Comment by JakeWharton** [comment]
Your image is not public. Try uploading to http://imgur.com and linking here with `![](link)`

**Comment by JakeWharton** [comment]
I don't see any incorrect behavior on API 7, 10, 15, or 16.

**Comment by akshaydashrath** [comment]
Added screenshot, its on API 16, the indicator at the bottom works fine if its style via code

**Comment by JakeWharton** [comment]
Thanks. Will try and reproduce.

**Comment by JakeWharton** [comment]
I can repro with the APK in 'Downloads' (and on the Play Store) but not with a development version that I deploy from the IDE.

**Comment by JakeWharton** [comment]
I am going to chalk this up to a bad release build when I made 2.4.0. I cannot reproduce on any development builds nor release builds, the logic is sound, and the styles are crafted correctly.

What probably happened was an error converting the styles XML to binary format which cased both the background color and indicator color to be identical.

**Comment by JakeWharton** [comment]
Fixed as part of #135.
