### ISSUE TITLE
Allow TabPageIndicator to be styled programatically at runtime

### ISSUE THREAD

**Issue by mr-thierry** [JakeWharton/ViewPagerIndicator#134]
I would like to be able to style a TabPageIndicator programmatically at runtime, similar to TitlePageIndicator setTextColor(), setSelectedColor(), etc.

Right now the only way to do it is to have a theme for each variation and set the theme at runtime.

**Comment by JakeWharton** [comment]
The `TabPageIndicator` is creating using real views rather than being drawn on a `Canvas` which necessitates using styles and drawables to style it. This simply cannot be done with Android's style system.

**Comment by arj154** [comment]
Is it possible to switch between drawables at runtime or would this again be a limitation of the way in which tabs are implemented? I was thinking of trying something simular to this answer;
http://stackoverflow.com/questions/18486571/is-it-possible-to-change-actionbar-tab-indicator-programmatically?answertab=votes#tab-top
