### ISSUE TITLE
FadingEdge in TabPageIndicator

### ISSUE THREAD

**Issue by rashiq** [JakeWharton/ViewPagerIndicator#136]
Hello,
I don't know if this has been fixed in the newser releases but I have HorizontalFadingEdge enabled, so if you have a lot of tabs and some of them can't get displayed, the ViewPagerIndicator will fade the edges. 

I tried to fix this by setting this in the TabPageIndicator class:

public void setHorizontalFadingEdgeEnabled(
            boolean horizontalFadingEdgeEnabled) {
        // TODO Auto-generated method stub
        horizontalFadingEdgeEnabled = false; 
        super.setHorizontalFadingEdgeEnabled(horizontalFadingEdgeEnabled);

but it did not work. 

I am not very experienced in custom Views, so I don't know if you have to call this somewhere. Please let me know how to fix the scrollingedge. Besides that, thank you very much for this library! :)

**Comment by JakeWharton** [comment]
I added fading edges to the styled sample for tabs.

**Comment by aoikle** [comment]
How about fading edge for TitlePageIndicator?
