### ISSUE TITLE
Nested (and binded) TitlePageIndicator instances

### ISSUE THREAD

**Issue by leodido** [JakeWharton/ViewPagerIndicator#14]
Hi,
is there a simple way to accomplish the task described in the issue's title ?

I've figured out some ideas:
- embed a TitlePageIndicator into each Fragment attached from the super FragmentActivity and its adapter
- (try to) modify the behaviour of the super TitlePageIndicator listener

Are this 2 ideas right in your opinion ? Or simply to achieve this result is necessary to write the code from scratch ?

Thanks,
leo.

**Comment by JakeWharton** [comment]
There's certainly nothing stopping you from creating nested indicators. The indicator widgets are dumb and rely simply on their binding as a listener to `ViewPager` events. You can place them anywhere you'd like as long as they have that binding. Where you are going to run into issues is figuring out how to create nested `ViewPager`s.

Like fragments inside fragments, I don't think pagers inside pagers is a supported configuration and I'm not sure how well the gesture detection would work in this state. If you can figure out this interaction properly (if it's even possible) then adding the indicators should be very trivial.
