### ISSUE TITLE
Not able to refresh ViewPager on Data change

### ISSUE THREAD

**Issue by shikhak** [JakeWharton/ViewPagerIndicator#141]
Hi Jake,

This is a great application and very useful. Right now I am using it in my app..

I am populating string[] CONTENT on TestFragmentAdapter with all the file's name stored in my SDcard..

My problem is  that with in my app using another activity , when I delete some of the files and then go back to ViewPager activity(via some button), it doesn't refresh its CONTENT data and instead display blank data because the file is not on SDcard anymore (Data which I am displaying on viewpager is actually reading all data from txt files on sdcard).

Please help me!!!..this is a great ViewPager indicator and I really want to use it..PLZZZZ..

this is how I am populating it

 private static File path = new File(Environment.getExternalStorageDirectory()+File.separator+"Shikhatxt");
     private static File[] files = path.listFiles();
     private static  String[] CONTENT = new String[files.length];
     private int mCount = CONTENT.length;

I am not able to figure out how to refresh this data every time I click on ViewPager Button...

Thanks

**Comment by SimonVT** [comment]
ViewPager is part of the official support library, and any questions regarding it should be asked on e.g. stackoverflow or the android developers mailing list.

**Comment by shikhak** [comment]
I thought since this framework is built by Jake, this is the right place to ask this question. Anyway I will post it on Stackoverflow..But If anyone can help me answer this question here, would be great.Thanks
