### ISSUE TITLE
how to dynamic add the page to the viewpager?

### ISSUE THREAD

**Issue by purefly** [JakeWharton/ViewPagerIndicator#151]
hi, i just want to add the page(Fragment) to the viewpager after sliding to the end, that is dynamic adding. but i don't konw how to deal with, would you help me? thx

**Comment by sdqhzhm** [comment]
adapter.notifyDataSetChanged() in Handler

**Comment by purefly** [comment]
thx. i try as you say but it do not work.

**Comment by JakeWharton** [comment]
This is a question about ViewPager and adapters which back them. ViewPager is part of the support library from Google. This project is only an indicator to show which page you are on. Your best bet would be to try StackOverflow or the official Android developer mailing list.

**Comment by patelatharva** [comment]
http://stackoverflow.com/questions/8060904/add-delete-pages-to-viewpager-dynamically

**Comment by Adnan9011** [comment]
try this , add / remove dynamically page in viewpager , it's work .
http://stackoverflow.com/questions/13664155/dynamically-add-and-remove-view-to-viewpager
