### ISSUE TITLE
Auto slide CirclePageIndicator

### ISSUE THREAD

**Issue by temonteiro** [JakeWharton/ViewPagerIndicator#153]
Is there any method that causes the CirclePageIndicator automatically switch between pages?

**Comment by JakeWharton** [comment]
Call [`setCurrentItem`](https://developer.android.com/reference/android/support/v4/view/ViewPager.html#setCurrentItem%28int%29) on the `ViewPager`.

**Comment by apkelly** [comment]
Try something like this...

  private Runnable incrementPage = new Runnable() {

```
@Override

public void run() {

  // Scroll view

  int currentItem = mViewPager.getCurrentItem();

  int maxItems = mViewPager.getAdapter().getCount();

  if (maxItems != 0) {

    mViewPager.setCurrentItem((currentItem + 1) % maxItems, true);

  } else {

    mViewPager.setCurrentItem(0, true);

  }

  handler.postDelayed(incrementPage, SCROLL_DELAY);

}
```

  };
Then in onStart()

```
    handler.removeCallbacks(incrementPage);

    handler.postDelayed(incrementPage, SCROLL_DELAY);
```

And in onStop()

```
handler.removeCallbacks(incrementPage);
```

On 31 October 2012 07:51, temonteiro notifications@github.com wrote:

> Is there any method that causes the CirclePageIndicator automatically
> switch between pages?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/JakeWharton/Android-ViewPagerIndicator/issues/153.

## 

_Phone: *+61 403 580 476
*Email:_ andrew.kelly@swizel-studios.com
_Website:_ www.swizel-studios.com
