### ISSUE TITLE
Creating Indicator from Fragment won't work

### ISSUE THREAD

**Issue by onigunn** [JakeWharton/ViewPagerIndicator#157]
Hi there,

I've included the indicator on Eclipse as library, all classes are resolved by compile time. But if I try to initialize an indicator, I receive this kind of exception

```
11-13 21:57:14.230: E/AndroidRuntime(6596): java.lang.NoClassDefFoundError:com.viewpagerindicator.R$attr
11-13 21:57:14.230: E/AndroidRuntime(6596):     at com.viewpagerindicator.CirclePageIndicator.<init>(CirclePageIndicator.java:72)
11-13 21:57:14.230: E/AndroidRuntime(6596):     at com.viewpagerindicator.CirclePageIndicator.<init>(CirclePageIndicator.java:68)
```

I've cleaned the project several times, tried to init the indicator programmatically all always end in this exception.

I'm using the latest support-lib version, target SDK ist 16.

Maybe this is important too:

```
11-13 22:16:18.850: W/dalvikvm(10440): VFY: unable to resolve static field 1555 (vpiCirclePageIndicatorStyle) in Lcom/viewpagerindicator/R$attr;
```

**Comment by jekopena** [comment]
Same problem here. It was working until I downloaded the last Android SDK Tools rev21 and the last ADT plugin for Eclipse.

**Comment by jekopena** [comment]
onigunn if this helps you, I have cleaned my project and the ViewPagerIndicator project, rebuilded them and now it's working again.

**Comment by imonhf** [comment]
@jekopena try to change the compliance level in your project properties. Right click on your project goto properties>java compiler> compiler compliance level try selecting 1.6.

**Comment by duncandee** [comment]
Update to the latest support. Lib

**Comment by onigunn** [comment]
jekopena - I can't count how many times I tried a clean / build.

I'll will update tonight to adt21 and try it again.

**Comment by onigunn** [comment]
jekopena - no luck with adt21 either.

**Comment by jekopena** [comment]
As I said, in my case it worked after cleaning and rebuilding both projects and it wasn't the first time I tried it. Also I already had compiler compliance level to 1.6. I don't know what it could be, sorry I can't help you.

**Comment by duncandee** [comment]
Update your support jar.

**Comment by onigunn** [comment]
Well duncandee mine is updated (was one of the first things I've done). Any other suggestions?

**Comment by duncandee** [comment]
What I did was cleanmy whole workspace. Restart eclipse. One eclipse
settles down run build. I hope you come right

**Comment by kpraveen72** [comment]
see this http://stackoverflow.com/questions/12126194/viewpagerindicator-classnotfoundexception/12127380#12127380. This is helpful and using this i resolved my issue

**Comment by endriu125** [comment]
Probably you finally resolved the problem but after updating to Android SDK Tools r21 or r22, you need to install also Android SDK Build Tools (you will see it only after restarting the Android SDK Manager).

**Comment by onigunn** [comment]
Closing because is not relevant anymore.
