### ISSUE TITLE
Possibility to set padding in Tab TextView.

### ISSUE THREAD

**Issue by ghost** [JakeWharton/ViewPagerIndicator#159]
Hi,

I don't seem to come up with a way of setting the padding for the tab text in the TabPageIndicator.

As far as I see in the code for adding a new tab there is now attribute passed to the TextView.

```
private void addTab(int index, CharSequence text, int iconResId) {
    final TabView tabView = new TabView(getContext());
    tabView.mIndex = index;
    tabView.setFocusable(true);
    tabView.setOnClickListener(mTabClickListener);
    tabView.setText(text);

    if (iconResId != 0) {
        tabView.setCompoundDrawablesWithIntrinsicBounds(iconResId, 0, 0, 0);
    }

    mTabLayout.addView(tabView, new LinearLayout.LayoutParams(0, MATCH_PARENT, 1));
}
```

Could this somehow be added? Because the padding of the text in the TabPageIndicator does not match the one in the tabs of the actiobar.

Thanks

M.

**Comment by SimonVT** [comment]
You can set it in your theme with the vpiTabPageIndicatorStyle attribute.
