### ISSUE TITLE
Rendering issues when using gmaps2 api in viewpager on certain devices

### ISSUE THREAD

**Issue by francisdb** [JakeWharton/ViewPagerIndicator#164]
We are having issues with certain devices where adding a google map (using the new maps api) inside the viewpager causes rendering/repaint issues.

I suspect some timing or opengl issues

So far reproducable with:
Samsung Galaxy SII (4.0.4)
Sony Experia U (2.3.7 and 4.0.4)

Works correctly on:
Samsing Galaxy ACE (2.3.7)
Samsung Galaxy SIII (4.1.x?))

I was able to isolate the issue with a simple viewpager, 3 page, map on the left, text views on the middle and right, the map always renders correctly, so does the righ-most textview, the center textview has the issue when swiping from the map, only the place where the map controls were show the actual textview as if a black layer with a hole is put on the list. Dragging actually drags the component beneath (visible through the hole) 

Causing a screen repaint by opening the options menu for example fixes the issue.

See added screenshot from our app on GS2

I'll add my demo app source later...

Any ideas / suggestions?

![maps_viewpager_issue](https://f.cloud.github.com/assets/161305/6942/4b120510-43de-11e2-9074-d9e442c7bbe3.jpg)

**Comment by JakeWharton** [comment]
This sounds like a `ViewPager` bug (from the support library) and not anything to do with ViewPagerIndicator.

**Comment by francisdb** [comment]
Okay, I'll close this, try to reproduce on my S2 without Android-ViewPagerIndicator and post a bug to google. I fear they won't reply as fast as you. Thanks
