### ISSUE TITLE
How to display a part of left/right title in TitlePageIndicator

### ISSUE THREAD

**Issue by tatung** [JakeWharton/ViewPagerIndicator#171]
Hi, 

I'm using TitlePageIndicator. The indicator has worked very find until I set the title to a little bit long string (20 characters), the center title is displayed very well but the left and the right title is too closed to the center title. Is there any way to make it just like in Google play where the left and the right title is showed only half (or a fix length)?

Thank you,

**Comment by ghost** [comment]
Did you find a solution for that?

**Comment by tatung** [comment]
@Baili-Samy: please check on the answer of this link
http://stackoverflow.com/questions/14173919/jakewharton-titlepageindicator-how-to-display-only-half-of-right-and-left-title/14230006#14230006
