### ISSUE TITLE
Fragment Transition Is Not Working As Expected

### ISSUE THREAD

**Issue by chintamani** [JakeWharton/ViewPagerIndicator#173]
```
       I  have used ViewPagerIndicator library to support the fragment functionality. But  I am facing one serious problem. 

      The problem is I am not able to perform expected fragment transition.  When I am starting the application, initially getItem() method loads first and second fragment simultaneously, expected only single fragment at a time. As a result when I perform fragment transaction from first to second, getItem() loads remaining (i.e. third ) fragment and calls the same fragment. 

     Henceforth I am not able to perform expected fragment transition. 
```

   Waiting eagerly for the solution..

Thanks in advance.

**Comment by JakeWharton** [comment]
Fragments are provided by the support library which is from Google. Try the official developer mailing list or StackOverflow.

**Comment by chintamani** [comment]
I have checked it. But initially the getItem() method called twice and loading two fragments at a time. Is it the expected behavior..? How do I restrict it from loading two fragments simultaneously..?

**Comment by masheransari** [comment]
same issue occur in my FragmentPagerAdapter class. Dear all how can i fix this issue..??

**Comment by Sugarya** [comment]
@masheransari  you can used ViewPager.OnPageChangeListener listener on ViewPager itself for your purpose, and it works for me

**Comment by Sugarya** [comment]
@masheransari you can use ViewPager.OnPageChangeListener listener on ViewPager itself for your purpose, and it works for me
