### ISSUE TITLE
Enable scrolling when CirclePageIndicator has too much page

### ISSUE THREAD

**Issue by ghost** [JakeWharton/ViewPagerIndicator#178]
Hi,

I have binded a CirclePageIndicator with a ViewPager with approximatly 130 pages. The result is that the CirclePageIndicator draws ~130 bullets that cannot fit the parent layout. The CirclePageIndicator is partially visible.

Is it possible to scroll the CirclePageIndicator in relation to the ViewPager scroll ?

Anyway thanks for your libs ;)

Flavien

**Comment by JakeWharton** [comment]
I'm not sure the circle indicator is the correct one to use with 130+ pages. Perhaps you should use a simple `TextView` that says "Page 3 of 130".

**Comment by ghost** [comment]
That's a better solution. It's what happens when you post an issue without thinking about it more than 5 minutes.

Thanks a lot
