### ISSUE TITLE
Support v4 version being used causes issues

### ISSUE THREAD

**Issue by christopherperry** [JakeWharton/ViewPagerIndicator#188]
Hey Jake,

Since you're referencing the v4 r7 lib on central, it's causing me a huge headache trying to build with the latest v4 version using the maven android sdk deployer. There's some stuff I really need to use in the latest version. What do I have to do, fork and just work off of a different version in my branch?

**Comment by JakeWharton** [comment]
Just deploy r11 to your local repo or a Nexus and reference that. Maven will always choose the newest version.

**Comment by christopherperry** [comment]
r11 is in my local repo, the reference is in the form:

``` XML
    <dependency>
      <groupId>android.support</groupId>
      <artifactId>compatibility-v4</artifactId>
      <version>11</version>
    </dependency>
```

required by the maven android sdk deployer, and the way your lib declares the dependency is completely different.

**Comment by JakeWharton** [comment]
Mine is correct. Change the `groupId` and `artifactId` that the SDK deployer uses (or just deploy it manually yourself). Or use `<excludes>` to remove the dependency from this library. The former is a better option, though.

**Comment by christopherperry** [comment]
`<excludes>` causes other build issues. Ugh, I though Maven was going to make my life easier.

**Comment by JakeWharton** [comment]
So far as I can see your problem is with either Google not updating the support library version in central or Manfred not using the correct `groupId` and `artifactId` in his deployer. Maven's doing exactly what it's supposed to in this case.

**Comment by christopherperry** [comment]
Maybe this is an issue for the deployer, but shouldn't it be deploying to the correct repo?

**Comment by christopherperry** [comment]
I think both of those problems are in effect lol.

**Comment by JakeWharton** [comment]
Deploying .jars manually is pretty straightforward and a one-liner: 

```
mvn deploy:deploy-file -DgroupId=<group-id> \
  -DartifactId=<artifact-id> \
  -Dversion=<version> \
  -Dpackaging=jar \
  -Dfile=<path-to-file>
```

**Comment by christopherperry** [comment]
This worked

`mvn install:install-file -Dfile=android-support-v4.jar -DgroupId=com.google.android -DartifactId=support-v4 -Dversion=r11 -Dpackaging=jar`
