### ISSUE TITLE
SampleTitlesWithListener crash

### ISSUE THREAD

**Issue by ivanbartsov** [JakeWharton/ViewPagerIndicator#19]
Hey Jake,

there's still an error in SampleTitlesWithListener activity name:

``` xml
<activity
            android:name=".sample.sample.SampleTitlesWithListener
```

which causes the sample app to crash with class not found exception while trying to load it

Cheers

**Comment by JakeWharton** [comment]
Good catch. Thanks! Will update APK in the Market and on the downloads page soon.
