### ISSUE TITLE
Can't change the font size in TabPageIndicator

### ISSUE THREAD

**Issue by naddaf** [JakeWharton/ViewPagerIndicator#196]
Hi.

I am trying to change the style of the TabPageIndicator and I am successful in changing everything I want (like background image, text color, padding, ...) but I am not able to change the font size. I have a custom style for my application and there I have defined the style

``` xml
<style name="myStyle" parent="@style/Theme.HoloEverywhereDark.Sherlock.ForceOverflow">
    <item name="vpiTabPageIndicatorStyle">@style/CustomTabPageIndicator</item>
    ....
</style>

<style name="CustomTabPageIndicator" >
    <item name="android:gravity">center</item>
    <item name="android:background">@drawable/my_tab_indicator</item>        
    <item name="android:paddingTop">12dp</item>
    <item name="android:paddingBottom">12dp</item>
    <item name="android:paddingLeft">22dip</item>
    <item name="android:paddingRight">22dip</item>
    <item name="android:textSize">5sp</item>
    <item name="android:maxLines">1</item>
    <item name="android:textColor">#FF555555</item>
</style>
```

But I can't get the textSize attribute make any difference. Any idea what I an doing wrong?

Thanks
Ali.

**Comment by naddaf** [comment]
Issue was due to the old version of the library that was in my workspace; updating the library and making adjustment got things moving.

**Comment by ChinaSunHZ** [comment]
I want change TabPageIndicator footerColor / selectedColor and on more.
Please tell me change method.

In reply here or send email to me all ok.

My email  : China.SunHZ@Gmail.com

Thank you very much!!
