### ISSUE TITLE
Excluding support library dependency does not work

### ISSUE THREAD

**Issue by deckerj** [JakeWharton/ViewPagerIndicator#206]
I want to use the newest Android support library instead of the version coming with Viewpageindicator.

Although, I already tried the approach mentioned here with ActionBarSherlock (https://groups.google.com/forum/#!msg/actionbarsherlock/2cLR48IArck/70IfYCrr-pwJ), I still get the error depite the exlusion in the pom.

```
 <dependency>
         <groupId>com.viewpagerindicator</groupId>
         <artifactId>library</artifactId>
         <version>2.4.1</version>
         <type>apklib</type>
         <exclusions>
                <exclusion>
                    <groupId>com.google.android</groupId>
                    <artifactId>support-v4</artifactId>
                </exclusion>
         </exclusions>
</dependency>
```

[INFO] UNEXPECTED TOP-LEVEL EXCEPTION:
[INFO] java.lang.IllegalArgumentException: already added: Landroid/support/v4/app/LoaderManager;
[INFO]  at com.android.dx.dex.file.ClassDefsSection.add(ClassDefsSection.java:123)
[INFO]  at com.android.dx.dex.file.DexFile.add(DexFile.java:163)
[INFO]  at com.android.dx.command.dexer.Main.processClass(Main.java:490)
[INFO]  at com.android.dx.command.dexer.Main.processFileBytes(Main.java:459)
[INFO]  at com.android.dx.command.dexer.Main.access$400(Main.java:67)
[INFO]  at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:398)
[INFO]  at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:245)
[INFO]  at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:131)
[INFO]  at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:109)
[INFO]  at com.android.dx.command.dexer.Main.processOne(Main.java:422)
[INFO]  at com.android.dx.command.dexer.Main.processAllFiles(Main.java:333)
[INFO]  at com.android.dx.command.dexer.Main.run(Main.java:209)
[INFO]  at com.android.dx.command.dexer.Main.main(Main.java:174)
[INFO]  at com.android.dx.command.Main.main(Main.java:91)

**Comment by deckerj** [comment]
I solved the issue using the solution presented here: https://github.com/JakeWharton/Android-ViewPagerIndicator/issues/188

Still unclear, why the exlusion did not work though

**Comment by deckerj** [comment]
See also hints for support library on SDK-Deployer : https://github.com/mosabua/maven-android-sdk-deployer

**Comment by JakeWharton** [comment]
You'll have less of a headache if you just deploy it under the same groupId and artifactId with a bumped version. Maven is smart and will pick the newer version when you depend on both.
