### ISSUE TITLE
TabPageIndicator Change 

### ISSUE THREAD

**Issue by unripeapple1** [JakeWharton/ViewPagerIndicator#215]
TabPageIndicator Change the underline width and hegiht and color?

how to do? where i go fix it?

**Comment by JakeWharton** [comment]
There's a styled sample which demonstrates how to do this.

Basically you have to create your own theme for the tab style which uses a different background. The background is a state-list drawable that has 9-patches for the unselected, selected, pressed states. Despite not being used for the action bar tabs, you can generate the 9-patches and selector XML using @jgilfelt's [Action Bar Style Generator](http://jgilfelt.github.io/android-actionbarstylegenerator/).

**Comment by JakeWharton** [comment]
Here's the sample's selector XML: https://github.com/JakeWharton/Android-ViewPagerIndicator/blob/master/sample/res/drawable/custom_tab_indicator.xml

And the drawables are in the `drawable-xhdpi/`, `drawable-hdpi/`, and `drawable-mdpi/` folders. Here's the XHDPI stuff: https://github.com/JakeWharton/Android-ViewPagerIndicator/tree/master/sample/res/drawable-xhdpi

**Comment by unripeapple1** [comment]
Thx for your answer

i can't speak english well.. sorry 

just read think word..

read for sentence plz

I check ...     upper links

I got One Question 

if i change 9-patch image size 

bigger than older imgs 

tabindicator _____  <---like this

 change to size height ???

why i think 

no attribute........input size change

**Comment by nschwermann** [comment]
Annoyingly, these are all the wrong size with material specs.
