### ISSUE TITLE
CirclePageIndicator fires onPageSelected() too early

### ISSUE THREAD

**Issue by realdadfish** [JakeWharton/ViewPagerIndicator#218]
I'm using the CirclePageIndicator together with a FragmentStatePagerAdapter. If I have three pages managed through this adapter and I'm on the last page and send the application into the background and from there back to the foreground, I'm notified that the page selection changed to index 2. This is correct, however, at this time the fragment was not yet instantiated, so I have no way of doing fragment-specific operations, like changing the UI based on the currently active fragment.

Could the root of this problem bei in v4's ViewPager / FragmentStatePagerAdapter?

I figured that there is a call to populate() in http://grepcode.com/file/repo1.maven.org/maven2/com.google.android/support-v4/r7/android/support/v4/view/ViewPager.java#408 before onPageSelected() is fired and that inside populate() the adapter's finishUpdate() method is called that executes all pending fragment transactions immediately, but I wonder why the fragment is still not present. It gets properly re-created, obviously, _after_ the adapter fired.

**Comment by JakeWharton** [comment]
File on http://b.android.com. `ViewPager` is part of the support library from Google, not this library.

**Comment by realdadfish** [comment]
Well, CirclePageIndicator calls into my code, but it internally depends on ViewPager's onPageSelected. Sorry, I thought that this could be something that could affect / could be fixed in this library's code.

**Comment by realdadfish** [comment]
Just for reference: https://code.google.com/p/android/issues/detail?id=54525
