### ISSUE TITLE
Continuous Tab swipe

### ISSUE THREAD

**Issue by Antarix** [JakeWharton/ViewPagerIndicator#219]
I was wondering if there could be continuous tab swipe like in android home screen. I didn't found anywhere, please help me if its already available

**Comment by WuShaojun** [comment]
What continuous tab swipe means? Would you please give out a definite example?

**Comment by Antarix** [comment]
If i have total 3 tabs (tab1,tab2 and tab3) and i started swiping from tab1 > tab2 > tab3 , now when i reach to tab3 and  swipe further it should go back to tab1

**Comment by WuShaojun** [comment]
I have run this project, just found that this function is not available. I think it can be add into to perfect the project.

**Comment by Antarix** [comment]
Ya would be great if added to it

**Comment by WuShaojun** [comment]
Yes, I think it is a good idea!

**Comment by SimonVT** [comment]
It'd have to be supported by ViewPager before this library can handle it, so file an issue on b.android.com and request that they implement it.
