### ISSUE TITLE
ActionBar Sherlock example in sample application

### ISSUE THREAD

**Issue by ai212983** [JakeWharton/ViewPagerIndicator#22]
Is ViewPagerIndicator still compatible with ActionBar Sherlock? No sign of the latter in the sample application. Was it removed for some reason?

**Comment by JakeWharton** [comment]
It is compatible with ABS v3.3.x and earlier. It _may_ work with the `dev` branch of ABS which is now using the most recent revision of the Google compat lib.

Follow #20 for information as to when this project will be updated to support the new ACL revision and thus ABS 3.4+.

The reason that it's not in the ABS samples is that I don't want to introduce an external dependency. When ADT is updated to allow shipping library projects with resources as a single binary then I'll likely add it.

**Comment by ai212983** [comment]
Thanks for clarification, Jake.

I'd suggested removal of screenshot # 5 of sample application then, as it has ActionBar and kinda misleading - because of it I was expecting it in sample app.
