### ISSUE TITLE
TitlePageIndicator issue when calling onDraw method

### ISSUE THREAD

**Issue by djerom** [JakeWharton/ViewPagerIndicator#24]
Hi Jake,

I use Android-ViewPagerIndicator classes on my project and I have noticed an issue when calling onDraw method of TitlePageIndicator class.
This issue is specific to an Android target environment < Android 2.2 (API level 8).

Stack:

```
11-05 13:30:36.290: E/AndroidRuntime(209): Uncaught handler: thread main exiting due to uncaught exception
11-05 13:30:36.300: E/AndroidRuntime(209): java.lang.IndexOutOfBoundsException: Invalid location 0, size is 0
11-05 13:30:36.300: E/AndroidRuntime(209):  at java.util.ArrayList.get(ArrayList.java:353)
11-05 13:30:36.300: E/AndroidRuntime(209):  at com.hencky.discography.ui.widget.TitlePageIndicator.onDraw(TitlePageIndicator.java:314)
11-05 13:30:36.300: E/AndroidRuntime(209):  at android.view.View.draw(View.java:6274)
11-05 13:30:36.300: E/AndroidRuntime(209):  at android.view.ViewGroup.drawChild(ViewGroup.java:1526)
11-05 13:30:36.300: E/AndroidRuntime(209):  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1256)
11-05 13:30:36.300: E/AndroidRuntime(209):  at android.view.View.draw(View.java:6277)
11-05 13:30:36.300: E/AndroidRuntime(209):  at android.view.ViewGroup.drawChild(ViewGroup.java:1526)
11-05 13:30:36.300: E/AndroidRuntime(209):  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1256)
11-05 13:30:36.300: E/AndroidRuntime(209):  at android.view.ViewGroup.drawChild(ViewGroup.java:1524)
11-05 13:30:36.300: E/AndroidRuntime(209):  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1256)
11-05 13:30:36.300: E/AndroidRuntime(209):  at android.view.View.draw(View.java:6277)
11-05 13:30:36.300: E/AndroidRuntime(209):  at android.widget.FrameLayout.draw(FrameLayout.java:352)
11-05 13:30:36.300: E/AndroidRuntime(209):  at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:1883)
11-05 13:30:36.300: E/AndroidRuntime(209):  at android.view.ViewRoot.draw(ViewRoot.java:1332)
11-05 13:30:36.300: E/AndroidRuntime(209):  at android.view.ViewRoot.performTraversals(ViewRoot.java:1097)
11-05 13:30:36.300: E/AndroidRuntime(209):  at android.view.ViewRoot.handleMessage(ViewRoot.java:1613)
11-05 13:30:36.300: E/AndroidRuntime(209):  at android.os.Handler.dispatchMessage(Handler.java:99)
11-05 13:30:36.300: E/AndroidRuntime(209):  at android.os.Looper.loop(Looper.java:123)
11-05 13:30:36.300: E/AndroidRuntime(209):  at android.app.ActivityThread.main(ActivityThread.java:4203)
11-05 13:30:36.300: E/AndroidRuntime(209):  at java.lang.reflect.Method.invokeNative(Native Method)
11-05 13:30:36.300: E/AndroidRuntime(209):  at java.lang.reflect.Method.invoke(Method.java:521)
11-05 13:30:36.300: E/AndroidRuntime(209):  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:791)
11-05 13:30:36.300: E/AndroidRuntime(209):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:549)
11-05 13:30:36.300: E/AndroidRuntime(209):  at dalvik.system.NativeStart.main(Native Method)
```

A simple fix could be a test on bounds size :

``` java
protected void onDraw(Canvas canvas) {
        super.onDraw(canvas);

        // Calculate views bounds
        ArrayList<RectF> bounds = calculateAllBounds(mPaintText);

        if (bounds.size() > 0) {
            final int count = mViewPager.getAdapter().getCount();
            final int countMinusOne = count - 1;
            ...
            ...
}
```

**Comment by JakeWharton** [comment]
Somehow overlooked this for 2.0. Will patch both circle and title indicators to be more graceful when unbound or bound to empty adapters for a 2.0.1 very soon.

**Comment by funston** [comment]
Wierd. I have the latest code and seeing this fairly frequently still.

E/AndroidRuntime( 3964): java.lang.IndexOutOfBoundsException: Invalid index 8, size is 1
E/AndroidRuntime( 3964):    at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:257)
E/AndroidRuntime( 3964):    at java.util.ArrayList.get(ArrayList.java:311)
E/AndroidRuntime( 3964):    at android.widget.HeaderViewListAdapter.getView(HeaderViewListAdapter.java:225)
E/AndroidRuntime( 3964):    at android.widget.AbsListView.obtainView(AbsListView.java:1430)
E/AndroidRuntime( 3964):    at android.widget.ListView.measureHeightOfChildren(ListView.java:1280)
E/AndroidRuntime( 3964):    at android.widget.ListView.onMeasure(ListView.java:1191)
E/AndroidRuntime( 3964):    at android.view.View.measure(View.java:8243)
E/AndroidRuntime( 3964):    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:3132)
E/AndroidRuntime( 3964):    at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1012)
E/AndroidRuntime( 3964):    at android.widget.LinearLayout.measureVertical(LinearLayout.java:381)
E/AndroidRuntime( 3964):    at android.widget.LinearLayout.onMeasure(LinearLayout.java:304)
E/AndroidRuntime( 3964):    at android.view.View.measure(View.java:8243)
E/AndroidRuntime( 3964):    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:3132)
E/AndroidRuntime( 3964):    at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1012)
E/AndroidRuntime( 3964):    at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:696)
E/AndroidRuntime( 3964):    at android.widget.LinearLayout.onMeasure(LinearLayout.java:306)
E/AndroidRuntime( 3964):    at android.view.View.measure(View.java:8243)
E/AndroidRuntime( 3964):    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:3132)
E/AndroidRuntime( 3964):    at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1012)
E/AndroidRuntime( 3964):    at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:696)
E/AndroidRuntime( 3964):    at android.widget.LinearLayout.onMeasure(LinearLayout.java:306)
E/AndroidRuntime( 3964):    at android.view.View.measure(View.java:8243)
E/AndroidRuntime( 3964):    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:3132)
E/AndroidRuntime( 3964):    at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1012)
E/AndroidRuntime( 3964):    at android.widget.LinearLayout.measureVertical(LinearLayout.java:381)
E/AndroidRuntime( 3964):    at android.widget.LinearLayout.onMeasure(LinearLayout.java:304)
E/AndroidRuntime( 3964):    at android.view.View.measure(View.java:8243)
E/AndroidRuntime( 3964):    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:3132)
E/AndroidRuntime( 3964):    at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1012)
E/AndroidRuntime( 3964):    at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:696)
E/AndroidRuntime( 3964):    at android.widget.LinearLayout.onMeasure(LinearLayout.java:306)
E/AndroidRuntime( 3964):    at android.view.View.measure(View.java:8243)
E/AndroidRuntime( 3964):    at android.view.ViewGroup.measureChild(ViewGroup.java:3103)
E/AndroidRuntime( 3964):    at android.view.ViewGroup.measureChildren(ViewGroup.java:3080)
E/AndroidRuntime( 3964):    at android.widget.AbsoluteLayout.onMeasure(AbsoluteLayout.java:63)
E/AndroidRuntime( 3964):    at android.view.View.measure(View.java:8243)
E/AndroidRuntime( 3964):    at android.view.ViewGroup.measureChild(ViewGroup.java:3103)
E/AndroidRuntime( 3964):    at android.view.ViewGroup.measureChildren(ViewGroup.java:3080)
E/AndroidRuntime( 3964):    at android.widget.AbsoluteLayout.onMeasure(AbsoluteLayout.java:63)
E/AndroidRuntime( 3964):    at android.view.View.measure(View.java:8243)
E/AndroidRuntime( 3964):    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:3132)
E/AndroidRuntime( 3964):    at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1012)
E/AndroidRuntime( 3964):    at android.widget.LinearLayout.measureVertical(LinearLayout.java:381)
E/AndroidRuntime( 3964):    at android.widget.LinearLayout.onMeasure(LinearLayout.java:304)
E/AndroidRuntime( 3964):    at android.view.View.measure(View.java:8243)
E/AndroidRuntime( 3964):    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:3132)
E/AndroidRuntime( 3964):    at android.widget.FrameLayout.onMeasure(FrameLayout.java:245)
E/AndroidRuntime( 3964):    at android.view.View.measure(View.java:8243)
E/AndroidRuntime( 3964):    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:3132)
E/AndroidRuntime( 3964):    at android.widget.FrameLayout.onMeasure(FrameLayout.java:245)
E/AndroidRuntime( 3964):    at android.view.View.measure(View.java:8243)
E/AndroidRuntime( 3964):    at android.view.ViewRoot.performTraversals(ViewRoot.java:801)
E/AndroidRuntime( 3964):    at android.view.ViewRoot.handleMessage(ViewRoot.java:1727)
E/AndroidRuntime( 3964):    at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 3964):    at android.os.Looper.loop(Looper.java:123)
E/AndroidRuntime( 3964):    at android.app.ActivityThread.main(ActivityThread.java:4627)
E/AndroidRuntime( 3964):    at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 3964):    at java.lang.reflect.Method.invoke(Method.java:521)
E/AndroidRuntime( 3964):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:871)
E/AndroidRuntime( 3964):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)
E/AndroidRuntime( 3964):    at dalvik.system.NativeStart.main(Native Method)
E/MediaPlayer( 3964): message received msg=3, ext1=65, ext2=0
E/MediaPlayer( 3964): callback application
E/MediaPlayer( 3964): back from callback

**Comment by JakeWharton** [comment]
That stack trace doesn't seem to be originating from a ViewPagerIndicator widget but rather from a `ListView` implementation of some sort.
