### ISSUE TITLE
ViewPager Indicator not scrolling with ListFragment

### ISSUE THREAD

**Issue by necronet** [JakeWharton/ViewPagerIndicator#25]
I'm not quite sure if this is a problem with ViewPager Indicator with the ListFragment or the ScrollView, but it seems that when I used this component the Indicator does not  change it hold staticlly any ideas on how can solved this?

¿ Is this a bug ?

**Comment by JakeWharton** [comment]
Can you be more specific? The indicator only works for the left/right paging of the compatibility libraries `ViewPager`. It does not matter the type of view that you place inside the pager.

**Comment by necronet** [comment]
As you can see the indicator is not moving the Titles does not move from View to View it just stay staticlly, http://imageshack.us/photo/my-images/46/device20111122160259.png/ any ideas why this might happen?

**Comment by JakeWharton** [comment]
Are you setting a listener on the pager because that will overwrite the one
the indicator sets. If you have a custom listener you can set it on the
listener itself rather than the pager. It will forward all events.

---

Jake Wharton
http://about.me/jakewharton
On Nov 22, 2011 5:11 PM, "Jose Ayerdis" <
reply@reply.github.com>
wrote:

**Comment by necronet** [comment]
you are right I remove this and it work:

``` java
pager.setOnPageChangeListener(new OnPageChangeListener() {

        });
```

Nevertheless I did not get the " If you have a custom listener you can set it on the
listener itself rather than the pager" what do you mean?

**Comment by JakeWharton** [comment]
You should call `setOnPageChangeListener` on the indicator object rather than the pager like so:

https://github.com/JakeWharton/Android-ViewPagerIndicator/blob/master/sample/src/com/viewpagerindicator/sample/SampleTitlesWithListener.java#files
