### ISSUE TITLE
Handling the deprecation of setBackgroundDrawable

### ISSUE THREAD

**Issue by emptyway** [JakeWharton/ViewPagerIndicator#251]
setBackgroundDrawable() has been deprecated in API level 16: JELLY_BEAN.

Affected Files:
library/src/com/viewpagerindicator/UnderlinePageIndicator.java
library/src/com/viewpagerindicator/LinePageIndicator.java 
library/src/com/viewpagerindicator/CirclePageIndicator.java 
library/src/com/viewpagerindicator/TitlePageIndicator.java 

setBackground() should be called when the device sdk version is JELLY_BEAN or higher, and setBackgroundDrawable() is called when the device sdk version is less than JELLY_BEAN.

**Comment by JakeWharton** [comment]
They do the exact same thing. Deprecated doesn't mean not working.
