### ISSUE TITLE
How to make execute asynctask on View Pager only page selected / opened?

### ISSUE THREAD

**Issue by emjea** [JakeWharton/ViewPagerIndicator#256]
How to make execute asynctask on View Pager only page selected / opened?
like friendcaster for android execute asynctask when page opened. Or like tabhost method only execute when page opened, but when move to other tabs and back again not reload again.
thanks before. :D

**Comment by JakeWharton** [comment]
ViewPager comes from the support library from Google. You should ask on the Android developers group or StackOverflow.
