### ISSUE TITLE
Update the TabPageIndicator page title 

### ISSUE THREAD

**Issue by trant** [JakeWharton/ViewPagerIndicator#258]
Hi there! 

I would like to update the tab bar page title without having to call notifyDataSetChanged(), causing the fragments to be recreated again. Is this possible?

**Comment by JakeWharton** [comment]
No. Your fragments shouldn't be recreated on every call to `notifyDataSetChanged` anyway. Look in the fragment manager to see if they already exist rather then creating every time.

**Comment by trant** [comment]
Hmm..How can I get the FragmentManager instance inside the adapter?

**Comment by JakeWharton** [comment]
Pass it in the constructor and keep it as a field.

**Comment by linyongsheng** [comment]
DDKEKX SNICUS
