### ISSUE TITLE
Title with bold face

### ISSUE THREAD

**Issue by LilDre** [JakeWharton/ViewPagerIndicator#261]
Hi!
I already put android:selectedBold="true" on com.viewpagerindicator.TabPageIndicator like: 
<com.viewpagerindicator.TabPageIndicator
        android:id="@+id/indicator2"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_below="@+id/titleBar"
        android:visibility="gone"
        android:selectedBold="true"
        android:background="#F7F0D0" />

But when title has been selected, title font wasn't turn bold.

How should I do with let the tile turn bold face?

**Comment by trietbui85** [comment]
Why this issue closed? Does android:selectedBold really work?
