### ISSUE TITLE
Lib Import Error

### ISSUE THREAD

**Issue by ghost** [JakeWharton/ViewPagerIndicator#29]
When i try to import the lib into Eclipse i get 
Multiple markers at this line
    - The type TitlePageIndicator must implement the inherited abstract method 
     PageIndicator.setViewPager(ViewPager)
    - The hierarchy of the type TitlePageIndicator is inconsistent
    - The type TitlePageIndicator must implement the inherited abstract method 
     PageIndicator.setViewPager(ViewPager, int)

I have posted more details here
http://stackoverflow.com/questions/8366133/android-importing-lib-project

**Comment by JakeWharton** [comment]
I have provided an answer. You needed only to add the Android Compatibility Library to your build path.
