### ISSUE TITLE
Possible fix for orientation change problem?

### ISSUE THREAD

**Issue by franciscojunior** [JakeWharton/ViewPagerIndicator#3]
Hi!

I'm seeing you are struggling the same way I was yesterday trying to fix the orientation change problem of the TitleViewIndicator.

I also tried everything but I always end up with a getWidth = 0 problem. 

The solution I came up was one which I still don't know if it is a hack or not but it works very well.

Just add the following line: 

currentScroll = currentPosition \* result;

Inside the method 

private int measureWidth(int measureSpec)

This single line does the trick :)

I hope it helps.

**Comment by JakeWharton** [comment]
I pretty much did the same thing but in the `onDraw` method. I eliminated the `mCurrentScroll` variable so that I could implement proper state saving when you change orientation.

**Comment by franciscojunior** [comment]
Ahh, that's awesome!!

I'l rewrite my code to use your library.

**Comment by JakeWharton** [comment]
I've added a bunch of other cool stuff too. Paging by clicking to the
left/right of indicator, theming via styles XML, and an underline indicator
on titles. Check the sample app for demos. A proper 1.0 release will be
tonight or tomorrow but the code should be stable as it stands now.

---

Jake Wharton
http://about.me/jakewharton
On Aug 5, 2011 5:00 PM, "franciscojunior" <
reply@reply.github.com>
wrote:

**Comment by franciscojunior** [comment]
That's great!! 

I was just about to add a new issue request when I saw your issue #1 and also noticed you commit!

Awesome job!

Vampidroid will get a much better interface lift on next version with ActionBar and ViewPagerIndicator :)
