### ISSUE TITLE
Use theme from application

### ISSUE THREAD

**Issue by JulienLevelUp** [JakeWharton/ViewPagerIndicator#30]
Hi,

I use your usefull library.
But it seems that the default values do not use the values of the theme applied on the application using Android Manifest.

Is it normal ?

**Comment by JakeWharton** [comment]
Using either a theme set on the activity or the application should be no different in the eyes of the library. Are you sure you are specifying the styles correctly in your theme? Would you mind showing both your manifest and your theme?

**Comment by JulienLevelUp** [comment]
Yes there is no problem.

The theme is also applied on others libraries. Only this does not use it.
