### ISSUE TITLE
Please remove 'android-support-v4.jar' from the package

### ISSUE THREAD

**Issue by davidshen84** [JakeWharton/ViewPagerIndicator#300]
My project needs google's support-v4 as well, but since you included this jar file in the package, the compiler is picking your version instead of google's. I saw in your `pom.xml` file that you have already define the google's support-v4 as a dependency, why I still include this jar as an unmanaged dependency? Can you please remove it? :)

**Comment by msdx** [comment]
```
compile ('com.viewpagerindicator:library:2.4.1') {
    // exclusion is not neccessary, but generally a good idea.
    exclude group: 'com.google.android', module: 'support-v4'
}
```

**Comment by msdx** [comment]
请叫我雷锋。@davidshen84
