### ISSUE TITLE
Android Studio Problem

### ISSUE THREAD

**Issue by ghost** [JakeWharton/ViewPagerIndicator#303]
I'm trying to use this with my Gradle project but it's giving me errors. Any solutions?

**Comment by philippeluickx** [comment]
Stackoverflow is your friend: http://stackoverflow.com/questions/21130003/using-viewpagerindicator-library-with-android-studio-and-gradle

**Comment by ghost** [comment]
Thanks! I really did look for something like this. Guess I'll have to look harder next time!
