### ISSUE TITLE
setOnPageChangeListener not working properly

### ISSUE THREAD

**Issue by Mehdiway** [JakeWharton/ViewPagerIndicator#310]
In order the change the background color at every page scroll, I'm using ViewPager's `setOnPageChangeListener` but it seems that when I use it, the ViewPager indicator stops working, I keep scrolling throw the pages but the indicators (IconPageIndicator in this case) keeps point to the first page.

```
// Dynamically change the background color as the user navigates through pages
viewPager.setOnPageChangeListener(new OnPageChangeListener() {
    @Override
    public void onPageSelected(int position) {
        ColorDrawable[] colors = {new ColorDrawable(backgroundColors[previousPosition]), new ColorDrawable(backgroundColors[position])};
        TransitionDrawable trans = new TransitionDrawable(colors);
        newFeaturesLayout.setBackgroundDrawable(trans);
        trans.startTransition(500);
        previousPosition = position;
    }

    @Override
    public void onPageScrolled(int arg0, float arg1, int arg2) {}

    @Override
    public void onPageScrollStateChanged(int arg0) {}
});
```

**Comment by JoeyZhao317** [comment]
Look the manual carefully:
1. (Optional) If you use an OnPageChangeListener with your view pager you should set it in the indicator rather than on the pager directly.
   
   //continued from above
   titleIndicator.setOnPageChangeListener(mPageChangeListener);
