### ISSUE TITLE
Slide tab indicator in TabPageIndicator

### ISSUE THREAD

**Issue by pkpio** [JakeWharton/ViewPagerIndicator#316]
Just like the CirclePageIndicator, where the dot indicating the current page slides along with the page (no snap enabled by default), is it possible to do that for the tab indicator? In the default implementation, it is discrete, the indicator changes discretely after the page change has been complete. Please take a look at https://github.com/astuetz/PagerSlidingTabStrip for more details. 

This is implementation of the tab indicator on GooglePlay (indicator sliding with the page).

**Comment by lightSky** [comment]
Yeah,I alreay applied this lib into my project.And there is  a tutorial  on google official website already.You can take a look.
http://developer.android.com/samples/SlidingTabsBasic/src/com.example.android.common/view/SlidingTabLayout.html

**Comment by pkpio** [comment]
Glad to know. It's funny, I was actually looking at that page a while ago and didn't pay good attention to it. Sorry about that. This is a great library. Good job. Keep it up :)
