### ISSUE TITLE
Incomplete TabPageIndicator sample

### ISSUE THREAD

**Issue by sudrich** [JakeWharton/ViewPagerIndicator#32]
The sample for the TabPageIndicator lacks color and the underlined style, not like in the sample application.

**Comment by JakeWharton** [comment]
The tab pager is fundamentally different from the other two in that it is comprised of Android widgets rather than completely drawn by hand. You define its look through styles and drawables.

I'll leave this issue open, however, as more samples are needed.

**Comment by sudrich** [comment]
I can't find attributes or correspondig styles for the TabPageIndicator like I can for the TitlePageIndicator.
Do I have to manipulate the tab-layout-resource of the library to alter the appearance or am I just too dumb to see the interface for that?

**Comment by JakeWharton** [comment]
You can see an example from the default styles provided with the library.

The two theme attributes: https://github.com/JakeWharton/Android-ViewPagerIndicator/blob/master/library/res/values/vpi__styles.xml#L21-22

The referenced styles for tab and text: https://github.com/JakeWharton/Android-ViewPagerIndicator/blob/master/library/res/values/vpi__styles.xml#L53-67

Override the attributes in your theme and provide styles which extend from the two provided.

**Comment by sudrich** [comment]
I might not see the solution due to my inexperience, but my problem is that the styles for the TabPageIndicator don't even seem to attach.
An implemented and compiled version of your sample doesn't show the preset padding of 22dip or the Nine-Patch backgroundresource. The styles are assigned in the layout-resource used for the TabView, so there shouldn't be any problem, right?

**Comment by erickok** [comment]
The style will attach if you add

```
<item name="vpiTabPageIndicatorStyle">@style/Widget.TabPageIndicator</item>
```

to your application's (or specific Activity's) theme.
