### ISSUE TITLE
TitlePageIndicator throws Exception when in non-Exactly Measured view

### ISSUE THREAD

**Issue by chrisbanes** [JakeWharton/ViewPagerIndicator#35]
TitlePageIndicator throws an IllegalStateException when it is used in a non-MeasureSpec.EXACTLY measured view.

Line 720-722:

``` java
if (specMode != MeasureSpec.EXACTLY) {
    throw new IllegalStateException(getClass().getSimpleName() + " can only be used in EXACTLY mode.");
}
```

I've commented out these lines and it works perfectly in a view measured using layout_weight. Infact, it's been working for the past 6/7 weeks and released in FriendCaster back then.

**Comment by JakeWharton** [comment]
This was a relic from the ViewFlow code. I never even thought to look at it. Thanks.

**Comment by chrisbanes** [comment]
Thanks!
