### ISSUE TITLE
Error:(1) Attribute "titleTextStyle" has already been defined

### ISSUE THREAD

**Issue by turingking** [JakeWharton/ViewPagerIndicator#354]
/home/king/AndroidStudioProjects/XingCheWang/app/build/intermediates/exploded-aar/com.viewpagerindicator/library/2.4.1/res/values/values.xml
Error:(1) Attribute "titleTextStyle" has already been defined
Error:(1) Attribute "subtitleTextStyle" has already been defined
Error:(1) Attribute "divider" has already been defined
Error:(1) Attribute "background" has already been defined
Error:(1) Attribute "backgroundSplit" has already been defined
Error:(1) Attribute "navigationMode" has already been defined
Error:(1) Attribute "displayOptions" has already been defined
Error:(1) Attribute "title" has already been defined
Error:(1) Attribute "subtitle" has already been defined
Error:(1) Attribute "icon" has already been defined
Error:(1) Attribute "logo" has already been defined
Error:(1) Attribute "backgroundStacked" has already been defined
Error:(1) Attribute "customNavigationLayout" has already been defined
Error:(1) Attribute "homeLayout" has already been defined
Error:(1) Attribute "progressBarStyle" has already been defined
Error:(1) Attribute "indeterminateProgressStyle" has already been defined
Error:(1) Attribute "progressBarPadding" has already been defined
Error:(1) Attribute "itemPadding" has already been defined
Error:(1) Attribute "initialActivityCount" has already been defined
Error:(1) Attribute "expandActivityOverflowButtonDrawable" has already been defined
Error:(1) Attribute "preserveIconSpacing" has already been defined
Error:(1) Attribute "iconifiedByDefault" has already been defined
Error:(1) Attribute "queryHint" has already been defined
Error:(1) Attribute "windowActionBar" has already been defined
Error:(1) Attribute "windowActionBarOverlay" has already been defined
Error:(1) Attribute "windowActionModeOverlay" has already been defined
Error:(1) Attribute "actionBarTabStyle" has already been defined
Error:(1) Attribute "actionBarTabBarStyle" has already been defined
Error:(1) Attribute "actionBarTabTextStyle" has already been defined
Error:(1) Attribute "actionOverflowButtonStyle" has already been defined
Error:(1) Attribute "actionBarStyle" has already been defined
Error:(1) Attribute "actionBarSplitStyle" has already been defined
Error:(1) Attribute "actionBarWidgetTheme" has already been defined
Error:(1) Attribute "actionBarSize" has already been defined
Error:(1) Attribute "actionBarDivider" has already been defined
Error:(1) Attribute "actionBarItemBackground" has already been defined
Error:(1) Attribute "actionMenuTextAppearance" has already been defined
Error:(1) Attribute "actionMenuTextColor" has already been defined
Error:(1) Attribute "actionModeStyle" has already been defined
Error:(1) Attribute "actionModeCloseButtonStyle" has already been defined
Error:(1) Attribute "actionModeBackground" has already been defined
Error:(1) Attribute "actionModeSplitBackground" has already been defined
Error:(1) Attribute "actionModeCloseDrawable" has already been defined
Error:(1) Attribute "actionModeShareDrawable" has already been defined
Error:(1) Attribute "actionModePopupWindowStyle" has already been defined
Error:(1) Attribute "textAppearanceLargePopupMenu" has already been defined
Error:(1) Attribute "textAppearanceSmallPopupMenu" has already been defined
Error:(1) Attribute "actionDropDownStyle" has already been defined
Error:(1) Attribute "dropdownListPreferredItemHeight" has already been defined
Error:(1) Attribute "spinnerDropDownItemStyle" has already been defined
Error:(1) Attribute "homeAsUpIndicator" has already been defined
Error:(1) Attribute "actionButtonStyle" has already been defined
Error:(1) Attribute "selectableItemBackground" has already been defined
Error:(1) Attribute "dividerVertical" has already been defined
Error:(1) Attribute "activityChooserViewStyle" has already been defined
Error:(1) Attribute "popupMenuStyle" has already been defined
Error:(1) Attribute "textAppearanceSearchResultTitle" has already been defined
Error:(1) Attribute "textAppearanceSearchResultSubtitle" has already been defined
Error:(1) Attribute "textColorSearchUrl" has already been defined
Error:(1) Attribute "listPreferredItemHeightSmall" has already been defined
Error:(1) Attribute "listPreferredItemPaddingLeft" has already been defined
Error:(1) Attribute "listPreferredItemPaddingRight" has already been defined
Error:(1) Attribute "dropDownListViewStyle" has already been defined
Error:(1) Attribute "listPopupWindowStyle" has already been defined
Error:(1) Attribute "textAppearanceListItemSmall" has already been defined
Error:Execution failed for task ':app:processDebugResources'.

> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/home/king/ide/android-sdk-linux/build-tools/22.0.1/aapt'' finished with non-zero exit value 1

**Comment by realtian123** [comment]
Attribute "textAppearanceListItemSmall" has already been defined?

**Comment by psh** [comment]
I saw this error in a project using the new material design support library.  I tracked it down and only see the issue when I pull in

```
compile 'com.android.support:appcompat-v7:23.0.0'
```

Hope this helps in tracking down the issue!

**Comment by linsea** [comment]
I encounter this kind of issue after adding this dependency:

```
 compile 'com.android.support:design:22.2.0'
```

<app>\build\intermediates\exploded-aar\com.viewpagerindicator\library\2.4.1\res\values\values.xml
Error:(2) Attribute "textAllCaps" has already been defined
Error:(2) Attribute "theme" has already been defined

**Comment by 401885064** [comment]
do  you  worked this  iusses??   can   you  tell   me?

**Comment by elsennov** [comment]
Why closed? I encountered the same problem. Is there any solution for this? I used 'com.android.support:design:23.1.1'

**Comment by turingking** [comment]
@elsennov @401885064
You must reference the other projects in the project has defined some of the properties, their names and support design-dependent properties in the name of the conflict. Or your project defines the attributes conflict attribute names and support design of dependence.
Sorry, the processing done before me is not good enough. My English is not good, these words are written by translation software.
