### ISSUE TITLE
"compatibility-v4-r4.jar" is missing

### ISSUE THREAD

**Issue by ghost** [JakeWharton/ViewPagerIndicator#40]
Hi, Today I imported your Library in Eclipse but evertime I try to build the sample.
I got this error:

<code>The container 'Maven Dependencies' references non existing library 'C:\Users\Cracksoldier.m2\repository\android\support\compatibility-v4\r4\compatibility-v4-r4.jar'</code>

I already checked this folder and it only contains the two following files:

<code>compatibility-v4-r4.jar.lastUpdated
compatibility-v4-r4.pom.lastUpdated</code>

Maven and the plugin is installed and works right. This the output of the Eclipse Console during the import
of your git repo:

<code>20.12.11 21:49:44 MEZ: [WARN] The POM for com.jayway.maven.plugins.android.generation2:android-maven-plugin:jar:3.0.0-alpha-10 is missing, no dependency information available
20.12.11 21:49:45 MEZ: [INFO] Using DEFAULT lifecycle mapping for MavenProject: com.viewpagerindicator:library:2.2.0 @ C:\Users\Cracksoldier\Workspace\parent\library\pom.xml.
20.12.11 21:49:45 MEZ: [WARN] The POM for android:android:jar:1.6_r3 is missing, no dependency information available
20.12.11 21:49:45 MEZ: [WARN] The POM for android.support:compatibility-v4:jar:r4 is missing, no dependency information available
20.12.11 21:49:45 MEZ: [WARN] The POM for com.jayway.maven.plugins.android.generation2:android-maven-plugin:jar:3.0.0-alpha-10 is missing, no dependency information available
20.12.11 21:49:45 MEZ: [WARN] The POM for com.jayway.maven.plugins.android.generation2:android-maven-plugin:jar:3.0.0-alpha-10 is missing, no dependency information available
20.12.11 21:49:45 MEZ: [INFO] Using NULL lifecycle mapping for MavenProject: com.viewpagerindicator:parent:2.2.0 @ C:\Users\Cracksoldier\Workspace\parent\pom.xml.
20.12.11 21:49:45 MEZ: [INFO] Using DEFAULT lifecycle mapping for MavenProject: com.viewpagerindicator:sample:2.2.0 @ C:\Users\Cracksoldier\Workspace\parent\sample\pom.xml.
20.12.11 21:49:45 MEZ: [WARN] The POM for android:android:jar:1.6_r3 is missing, no dependency information available
20.12.11 21:49:45 MEZ: [WARN] The POM for android.support:compatibility-v4:jar:r4 is missing, no dependency information available
20.12.11 21:49:45 MEZ: [INFO] Using DEFAULT lifecycle mapping for MavenProject: com.viewpagerindicator:library:2.2.0 @ C:\Users\Cracksoldier\Workspace\parent\library\pom.xml.
20.12.11 21:49:45 MEZ: [WARN] The POM for com.jayway.maven.plugins.android.generation2:android-maven-plugin:jar:3.0.0-alpha-10 is missing, no dependency information available
20.12.11 21:49:45 MEZ: [INFO] Using DEFAULT lifecycle mapping for MavenProject: com.viewpagerindicator:sample:2.2.0 @ C:\Users\Cracksoldier\Workspace\parent\sample\pom.xml.
20.12.11 21:49:45 MEZ: [WARN] The POM for android:android:jar:1.6_r3 is missing, no dependency information available
20.12.11 21:49:45 MEZ: [WARN] The POM for android.support:compatibility-v4:jar:r4 is missing, no dependency information available
20.12.11 21:49:45 MEZ: [INFO] Adding source folder /library/src
20.12.11 21:49:45 MEZ: [INFO] Adding source folder /sample/src
20.12.11 21:49:45 MEZ: [INFO] Adding source folder /sample/src
20.12.11 21:49:45 MEZ: [INFO] Project import completed 17 sec
20.12.11 21:49:47 MEZ: [WARN] The POM for com.jayway.maven.plugins.android.generation2:android-maven-plugin:jar:3.0.0-alpha-10 is missing, no dependency information available
20.12.11 21:49:47 MEZ: [INFO] Using DEFAULT lifecycle mapping for MavenProject: com.viewpagerindicator:library:2.2.0 @ C:\Users\Cracksoldier\Workspace\parent\library\pom.xml.
20.12.11 21:49:47 MEZ: [WARN] The POM for android:android:jar:1.6_r3 is missing, no dependency information available
20.12.11 21:49:47 MEZ: [WARN] The POM for android.support:compatibility-v4:jar:r4 is missing, no dependency information available
20.12.11 21:49:47 MEZ: [WARN] The POM for com.jayway.maven.plugins.android.generation2:android-maven-plugin:jar:3.0.0-alpha-10 is missing, no dependency information available
20.12.11 21:49:47 MEZ: [WARN] The POM for com.jayway.maven.plugins.android.generation2:android-maven-plugin:jar:3.0.0-alpha-10 is missing, no dependency information available
20.12.11 21:49:47 MEZ: [INFO] Using DEFAULT lifecycle mapping for MavenProject: com.viewpagerindicator:library:2.2.0 @ C:\Users\Cracksoldier\Workspace\parent\library\pom.xml.
20.12.11 21:49:47 MEZ: [WARN] The POM for android:android:jar:1.6_r3 is missing, no dependency information available
20.12.11 21:49:47 MEZ: [WARN] The POM for android.support:compatibility-v4:jar:r4 is missing, no dependency information available
20.12.11 21:49:47 MEZ: [INFO] Using DEFAULT lifecycle mapping for MavenProject: com.viewpagerindicator:sample:2.2.0 @ C:\Users\Cracksoldier\Workspace\parent\sample\pom.xml.
20.12.11 22:12:32 MEZ: [INFO] Updated index for repository: central|http://repo1.maven.org/maven2 in 1511023 ms
20.12.11 22:15:59 MEZ: [WARN] The POM for com.jayway.maven.plugins.android.generation2:android-maven-plugin:jar:3.0.0-alpha-10 is missing, no dependency information available
20.12.11 22:16:00 MEZ: [INFO] Using DEFAULT lifecycle mapping for MavenProject: com.viewpagerindicator:library:2.2.0 @ C:\Users\Cracksoldier\Workspace\parent\library\pom.xml.
20.12.11 22:16:00 MEZ: [WARN] The POM for android:android:jar:1.6_r3 is missing, no dependency information available
20.12.11 22:16:00 MEZ: [WARN] The POM for android.support:compatibility-v4:jar:r4 is missing, no dependency information available</code>

Where can I get this file. I already googled it but I couldnt find it yet. I hope someone can help me.

Best Regards
Cracksoldier

**Comment by JakeWharton** [comment]
You have to install it with the [maven-android-sdk-deployer](https://github.com/mosabua/maven-android-sdk-deployer) except it has since been updated to the r6 now. I'm going to deploy my own android artifacts to my personal repository to avoid having this problem again. If you're not explicitly using Maven you can just import it as a regular Android project into eclipse and it'll pick up the `.jar` from the `libs/` directory.

**Comment by ghost** [comment]
Hi, I already tried to Import it as a normal Project but the error with pom.xml file is still
there. I installed maven-android-sdk-deployer today with "mvn install" I will try if I can
with that.

Best Regards
Cracksoldier

**Comment by JakeWharton** [comment]
The current maven installer uses the r6 compat lib. You'll have to update the dependency in this project's `pom.xml` to match.

**Comment by ghost** [comment]
Hi, I hope I understood you right I edited the pom.xml in library folder from this

<code>
               <dependency>
                <groupId>android.support</groupId>
                <artifactId>compatibility-v4</artifactId>
                <version>${android.support.version}</version>
            </dependency>
</code>

to this

<code>
               <dependency>
                <groupId>android.support</groupId>
                <artifactId>compatibility-r6</artifactId>
                <version>${android.support.version}</version>
            </dependency>
</code>

Is that the right way?
Please dont think Im stupid I am new to Maven.

Edit:// I tried it but now I got this error. I changed all three pom.xml in the project

<code>
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for
com.viewpagerindicator:library:apklib:2.2.0
[WARNING] 'build.plugins.plugin.version' for com.jayway.maven.plugins.android.ge
neration2:maven-android-plugin is missing. @ line 36, column 12
[WARNING]
[WARNING] Some problems were encountered while building the effective model for
com.viewpagerindicator:sample:apk:2.2.0
[WARNING] 'build.plugins.plugin.version' for com.jayway.maven.plugins.android.ge
neration2:maven-android-plugin is missing. @ line 48, column 12
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten t
he stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support buildin
g such malformed projects.
[WARNING]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] Android-ViewPagerIndicator (Parent)
[INFO] Android-ViewPagerIndicator
[INFO] Android-ViewPagerIndicator Sample
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Android-ViewPagerIndicator (Parent) 2.2.0
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-install-plugin:2.3.1:install (default-install) @ parent ---
[INFO] Installing C:\Users\Cracksoldier\Downloads\JakeWharton-Android-ViewPagerI
ndicator-3db7585\pom.xml to C:\Users\Cracksoldier.m2\repository\com\viewpagerin
dicator\parent\2.2.0\parent-2.2.0.pom
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Android-ViewPagerIndicator 2.2.0
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for android.support:compatibility-v6:jar:r6 is missing, no dep
endency information available
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Android-ViewPagerIndicator (Parent) ............... SUCCESS [0.206s]
[INFO] Android-ViewPagerIndicator ........................ FAILURE [0.131s]
[INFO] Android-ViewPagerIndicator Sample ................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.469s
[INFO] Finished at: Wed Dec 21 17:57:08 CET 2011
[INFO] Final Memory: 10M/108M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project library: Could not resolve dependencie
s for project com.viewpagerindicator:library:apklib:2.2.0: Failure to find andro
id.support:compatibility-v6:jar:r6 in http://r.jakewharton.com/maven/release was
 cached in the local repository, resolution will not be reattempted until the up
date interval of com.jakewharton has elapsed or updates are forced -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyReso
lutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command

[ERROR]   mvn <goals> -rf :library
</code>

I also tried to use "r6" and "v6".

Edit 2:// Hi is it possible that you send me pom.xml that you use because I tried it for our now
and cant get it working. I tried "compatibility-v6", "compatibility-r6" and also experimented with
the android support version but nothing worked.

Best Regards
Cracksoldier

**Comment by ghost** [comment]
Sorry for Doublepost, I tried to import it again in Eclipse as new Projekt from existing Source
at First it does not show any errors when I assign ActionBarSherlock and this to the sample
projekt as libs. Then I got 1053 errors. I also retryed to install it through mvn but it still gives
me an error and I have tried every combination with "r6" in the depencies he cannot resolve the
depencies when I run "mvn install".

I have tried:

compatibility-v4-r6
compatibility-v6
compatibility-r6

In the depencies and mvn couldnt not resolve the depencies

Best Regards
Cracksoldier

**Comment by Mr-JoJo** [comment]
Same thing here:

[ERROR] Failed to execute goal on project library: Could not resolve dependencies for project com.vi
ewpagerindicator:library:apklib:2.2.1-SNAPSHOT: The following artifacts could not be resolved: andro
id:android:jar:1.6_r3, android.support:compatibility-v4:jar:r6: Could not find artifact android:andr
oid:jar:1.6_r3 in com.jakewharton (http://r.jakewharton.com/maven/release) -> [Help 1]

**Comment by JakeWharton** [comment]
You have to install both Android 1.6 and the compat lib using the maven SDK deployer for now.

`cd` to `platforms/platform-4/` and `extras/compatibility-v4/` in the deployer and run `mvn install` in each.

Hopefully the compat lib makes it into maven central soon so I can avoid this step.

Again, the project _is_ set up to be used as a normal Android project in eclipse too completely separate from maven. File, New, Project, Android, use existing sources, select `library/` folder.

**Comment by ghost** [comment]
THX for the help now it works. I hope I did not annoy you with this problem.

I knew that it was set up as an eclipse project but problem was that it after
import I got 1053 errors when I assigned the libs manually because my
eclipse did not take it automatically.

Best Regards
Cracksoldier
