### ISSUE TITLE
ViewPagerIndicator works only in fullscreen

### ISSUE THREAD

**Issue by tasomaniac** [JakeWharton/ViewPagerIndicator#42]
I have a tablet app that use two fragments in a screen.
I am using ViewPager inside of the first fragment. 
I want to add this viewpagerindicator on top of it. But it fails.
When I remove the second fragment, it works ok.
I guess the problem is it requires full screen.

**Comment by JakeWharton** [comment]
This should be fixed with the latest release. Previously we required either a `fill_parent` width or an exact size (`px`, `dp`, etc.).
