### ISSUE TITLE
Force close when removing page

### ISSUE THREAD

**Issue by meisteg** [JakeWharton/ViewPagerIndicator#50]
This seems to only be a problem with the Titles samples, and not the Tabs or Circles samples.  The "Remove Page" option removes the right-most page. When I'm on the right-most page and I chose the remove page menu option, the sample app will sometimes crash. However, sometimes the app behaves as expected and removes the tab and the new right-most page is selected. I wasn't able to determine what I was doing differently that sometimes causes the app to crash.

**Comment by ohhorob** [comment]
If you can provide a stack trace, that would help track it down. You should be able to get it from the logcat output of the device. If possible, please indicate which version of the example app you are using.

**Comment by meisteg** [comment]
Sorry, I should have provided that info in the first place.  I'm running version 2.2.2 of the sample app, which I downloaded from the market.  The logcat output of the crash is below:

01-16 16:16:36.299 23749 23749 D AndroidRuntime: Shutting down VM
01-16 16:16:36.299 23749 23749 W dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x40018560)
01-16 16:16:36.319 23749 23749 E AndroidRuntime: FATAL EXCEPTION: main
01-16 16:16:36.319 23749 23749 E AndroidRuntime: java.lang.IndexOutOfBoundsException: Invalid index 5, size is 5
01-16 16:16:36.319 23749 23749 E AndroidRuntime:    at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:257)
01-16 16:16:36.319 23749 23749 E AndroidRuntime:    at java.util.ArrayList.get(ArrayList.java:311)
01-16 16:16:36.319 23749 23749 E AndroidRuntime:    at com.viewpagerindicator.TitlePageIndicator.onDraw(TitlePageIndicator.java:447)
01-16 16:16:36.319 23749 23749 E AndroidRuntime:    at android.view.View.draw(View.java:6880)
01-16 16:16:36.319 23749 23749 E AndroidRuntime:    at android.view.ViewGroup.drawChild(ViewGroup.java:1646)
01-16 16:16:36.319 23749 23749 E AndroidRuntime:    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
01-16 16:16:36.319 23749 23749 E AndroidRuntime:    at android.view.ViewGroup.drawChild(ViewGroup.java:1644)
01-16 16:16:36.319 23749 23749 E AndroidRuntime:    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
01-16 16:16:36.319 23749 23749 E AndroidRuntime:    at android.view.View.draw(View.java:6883)
01-16 16:16:36.319 23749 23749 E AndroidRuntime:    at android.widget.FrameLayout.draw(FrameLayout.java:357)
01-16 16:16:36.319 23749 23749 E AndroidRuntime:    at android.view.ViewGroup.drawChild(ViewGroup.java:1646)
01-16 16:16:36.319 23749 23749 E AndroidRuntime:    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
01-16 16:16:36.319 23749 23749 E AndroidRuntime:    at android.view.ViewGroup.drawChild(ViewGroup.java:1644)
01-16 16:16:36.319 23749 23749 E AndroidRuntime:    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
01-16 16:16:36.319 23749 23749 E AndroidRuntime:    at android.view.View.draw(View.java:6883)
01-16 16:16:36.319 23749 23749 E AndroidRuntime:    at android.widget.FrameLayout.draw(FrameLayout.java:357)
01-16 16:16:36.319 23749 23749 E AndroidRuntime:    at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2094)
01-16 16:16:36.319 23749 23749 E AndroidRuntime:    at android.view.ViewRoot.draw(ViewRoot.java:1525)
01-16 16:16:36.319 23749 23749 E AndroidRuntime:    at android.view.ViewRoot.performTraversals(ViewRoot.java:1261)
01-16 16:16:36.319 23749 23749 E AndroidRuntime:    at android.view.ViewRoot.handleMessage(ViewRoot.java:1862)
01-16 16:16:36.319 23749 23749 E AndroidRuntime:    at android.os.Handler.dispatchMessage(Handler.java:99)
01-16 16:16:36.319 23749 23749 E AndroidRuntime:    at android.os.Looper.loop(Looper.java:130)
01-16 16:16:36.319 23749 23749 E AndroidRuntime:    at android.app.ActivityThread.main(ActivityThread.java:3806)
01-16 16:16:36.319 23749 23749 E AndroidRuntime:    at java.lang.reflect.Method.invokeNative(Native Method)
01-16 16:16:36.319 23749 23749 E AndroidRuntime:    at java.lang.reflect.Method.invoke(Method.java:507)
01-16 16:16:36.319 23749 23749 E AndroidRuntime:    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
01-16 16:16:36.319 23749 23749 E AndroidRuntime:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
01-16 16:16:36.319 23749 23749 E AndroidRuntime:    at dalvik.system.NativeStart.main(Native Method)
01-16 16:16:36.319  1698  2120 W ActivityManager:   Force finishing activity com.viewpagerindicator.sample/.SampleTitlesStyledLayout
01-16 16:16:36.839  1698  1723 W ActivityManager: Activity pause timeout for HistoryRecord{408f89c0 com.viewpagerindicator.sample/.SampleTitlesStyledLayout}

**Comment by JakeWharton** [comment]
Fixed in `dev` branch.
