### ISSUE TITLE
Title of TitlePageIndicator jump and blink at the end of animation if PageView has margin

### ISSUE THREAD

**Issue by tprochazka** [JakeWharton/ViewPagerIndicator#58]
Please try to add this

   mPager.setPageMargin(30);
   mPager.setPageMarginDrawable(android.R.drawable.screen_background_dark);

to the SampleTitlesDefault.java

And try swipe to the right, title will jump and blink at the end of slide. It doesn't happen if you slide back.

So currently is not possible use divider between fragments.

**Comment by JakeWharton** [comment]
Margins weren't available at the time of implementation so it's not surprising that it reacts incorrectly to them. I'll take a look when I get time. Thanks for reporting!
