### ISSUE TITLE
Remove the shadow

### ISSUE THREAD

**Issue by fuadhamidan** [JakeWharton/ViewPagerIndicator#59]
How do I remove this black shadow?

![](http://i1210.photobucket.com/albums/cc418/Vootsugu22/Untitled-2.png)

**Comment by JakeWharton** [comment]
It looks like you're using the `TabPageIndicator`? The shadow is an indication of the ability to scroll left or right. It's part of the `HortizontalScrollView`'s styling. You'd have to look at its styles to see if it can even be changed.

**Comment by fuadhamidan** [comment]
yapp, I use TabPageIndicator..
I've tried several ways but haven't found the solution
anyone can help?
