### ISSUE TITLE
how to add the view page indictor below the view pager?

### ISSUE THREAD

**Issue by nanick** [JakeWharton/ViewPagerIndicator#67]
Hi jake,

Thanks so much for the code .
I dont have an issue, but would like to have some clarifications.

I am using your  library to swipe between the screens in my app ,it works perfect.
But I need to have the circles in the bottom of the screen like in the case of the android home screen.
Can u  please help me  with some example  for implementing the same.

**Comment by nanick** [comment]
I was able to find it myself,  had errors earlier when trying to implement the same due to some other component.

**Comment by JakeWharton** [comment]
I believe all of the examples of the CirclePageIndicator in the sample app
place then below the ViewPager. The indicator is just a view, you can
position it anywhere you like as if it were just another view in your
layout.
On Mar 1, 2012 6:33 AM, "nanick" <
reply@reply.github.com>
wrote:
