### ISSUE TITLE
Attributes already defined error in vpi__attrs.xml

### ISSUE THREAD

**Issue by bjorncs** [JakeWharton/ViewPagerIndicator#68]
I am trying to convert my Android eclipse project to a Android Maven project. After I migrated to the maven version of this library I have been unable to compile the project. Maven gives me a compile error, output this information:

`[project folder]\target\unpack\apklibs\com.viewpagerindicator_library_apklib_2.2.3\res\values\vpi__attrs.xml:78: 
error: Attribute "textColor" has already been defined
[project folder]\target\unpack\apklibs\com.viewpagerindicator_library_apklib_2.2.3\res\values\vpi__attrs.xml:80: 
error: Attribute "textSize" has already been defined`

I am using a custom style for the tab indicators like this:

``` xml
<style name="Widget.TabPageIndicator.Custom" parent="Widget.TabPageIndicator">
        <item name="android:gravity">center_horizontal</item>
        <item name="android:background">@drawable/vpi__tab_indicator</item>
        <item name="android:paddingLeft">4dip</item>
        <item name="android:paddingRight">4dip</item>
        <item name="android:paddingTop">14dp</item>
        <item name="android:paddingBottom">14dp</item>
    </style>
    <style name="Widget.TabPageIndicator.Text.Custom" parent="Widget.TabPageIndicator.Text">
        <item name="android:textAppearance">@style/TextAppearance.TabPageIndicator</item>
        <item name="android:textColor">@color/vpi__dark_theme</item>
        <item name="android:textSize">13sp</item>
        <item name="android:textStyle">bold</item>
        <item name="android:maxLines">1</item>
    </style>
    <style name="TextAppearance.TabPageIndicator" parent="Widget"/>
```

My theme file looks like this:

``` xml
    <style name="MainTheme" parent="android:Theme.Black.NoTitleBar">
        <item name="vpiTabPageIndicatorStyle">@style/Widget.TabPageIndicator.Custom</item>
        <item name="vpiTabTextStyle">@style/Widget.TabPageIndicator.Text.Custom</item>
         ....
   </style>
```

**Comment by bjorncs** [comment]
Nvm, this was due a conflict with other another library I'm using, Madvertise. It had this attrs.xml file:

```
    <declare-styleable name = "de.madvertise.android.sdk.MadView">
        <attr name="secondsToRefresh" format="integer" />
        <attr name="backgroundColor" format="color" />
        <attr name="textSize" format="integer" />
        <attr name="textColor" format="color" />
        <attr name="isTestMode" format="boolean" />
        <attr name="bannerType" format="string" />
        <attr name="deliverOnlyText" format="boolean" />
        <attr name="animation" format="string" />         
    </declare-styleable>
```

No idea why the definition for attribute for textColor or textSize should conflict. But moving the definition (and removing those 2 attributes) to my Android project solved the problem. Do someone has a explanation for this conflict?

**Comment by Loda** [comment]
see https://code.google.com/p/android/issues/detail?id=22576

in short: 
- attr / ressource ID are global, even across libs.
- use prefix when declaring attrib / ressource.
