### ISSUE TITLE
Left title jumps, the right title does not

### ISSUE THREAD

**Issue by Hooorny** [JakeWharton/ViewPagerIndicator#69]
This belongs to the TitlePagerIndicator:

When I swipe between screens and the middle title needs too much space to show all titles on screen, the left title is "jumping" when I swipe to the left, while the right title is moving smoothly when I swipe to the right until the middle title has enough space to be fully shown.

**Comment by sealskej** [comment]
I can certainly confirm this.

**Comment by sealskej** [comment]
Try to put long Strings as titles and you will see it ;)

**Comment by evgenpush** [comment]
when will be bug fixed?

**Comment by scompt** [comment]
This is a duplicate of #101 as far as I can tell.
