### ISSUE TITLE
Little glitches when clicking in the tab

### ISSUE THREAD

**Issue by franciscojunior** [JakeWharton/ViewPagerIndicator#7]
Hi!

I noticed that when you click in a tab, a little glich happens. For a fraction os seconds, the name of the clicked tab appears in the middle of the indicator and just later the animation of scrolling occurs.

I could notice that in the honeycomb emulator. 

I think it may be the call to invalidate() inside setCurrentItem which is called by the OnTouch event.

**Comment by franciscojunior** [comment]
Got it.

It is fixed by removing the invalidate() calls in:

setCurrentItem() and OnPageSelected()

**Comment by JakeWharton** [comment]
When paging toward the right the title that is coming in to be the new center briefly flashes to the left title one frame before it becomes true center. I believe this has the same underlying cause as what you describe above.
