### ISSUE TITLE
TabPageIndicator styling Text

### ISSUE THREAD

**Issue by SylvainHocq** [JakeWharton/ViewPagerIndicator#71]
It seem it is not possible to style selected Text with TabPageIndicator.
I want to set another style for the selected Tab. For example bold and another color.

Thanks

**Comment by cesards** [comment]
Same problem here...

I've been having a look to the previous issues of this topic, and nothing...

I tried (with no effects...):

<com.viewpagerindicator.TabPageIndicator
        android:id="@+id/quickactions_indicator"
        android:padding="10dip"
        style="@style/Theme.PageIndicatorDefaults"
        android:layout_height="wrap_content"
        android:layout_width="match_parent"/>

<style name="Theme.PageIndicatorDefaults" parent="android:Theme">
        <item name="vpiTabPageIndicatorStyle">@style/Widget.TabPageIndicator</item>
        <item name="vpiTabTextStyle">@style/Widget.TabPageIndicator.Text</item>
    </style>
    

```
<style name="Widget.TabPageIndicator" parent="Widget">
    <item name="android:gravity">center_horizontal</item>
    <item name="android:background">@drawable/vpi__tab_indicator</item>
    <item name="android:paddingLeft">22dip</item>
    <item name="android:paddingRight">22dip</item>
    <item name="android:paddingTop">12dp</item>
    <item name="android:paddingBottom">12dp</item>
</style>

<style name="Widget.TabPageIndicator.Text" parent="Widget">
    <item name="android:textAppearance">@style/TextAppearance.TabPageIndicator</item>
    <item name="android:textColor">@color/vpi__dark_theme</item>
    <item name="android:textSize">12sp</item>
    <item name="android:textStyle">bold</item>
    <item name="android:maxLines">1</item>
</style>
```

**Comment by abhilashlr** [comment]
How do you make the selected tab text to be bold?
