### ISSUE TITLE
VPI is not compatible with ABS-3 and ADT-17

### ISSUE THREAD

**Issue by kzotin** [JakeWharton/ViewPagerIndicator#73]
Please check recent ADT changes:
http://tools.android.com/recent/dealingwithdependenciesinandroidprojects

The way to solve the issue is to remove Support lib from VPI, and make it dependent on ABS.

**Comment by SimonVT** [comment]
VPI is not dependant on ABS tho, it's dependant on the support lib.
ABS3 is deprecated, while ABS4 uses the unmodified support lib. ADT17s new dependency management was made to deal with two projects including the same library.

**Comment by JakeWharton** [comment]
Yeah I'd classify this as an ABSv3 bug. I highly recommend you update to version 4 of ActionBarSherlock.
