### ISSUE TITLE
Add new revision of the support library to the VPI project

### ISSUE THREAD

**Issue by rfgamaral** [JakeWharton/ViewPagerIndicator#75]
The new ADT 17 has been released and with that came a new revision of the support library. Though this doesn't have any advantage on VPI it does help others who use VPI and need the extra stuff in the new revision.

Including VPI in our projects also includes the support library attached to the VPI project and we cannot include the new support library revision in our projects because that will conflict with the one in VPI.

Yes we can replace the one in VPI but will give us conflicts when pulling new commits if the support library is not updated in the repo.

**Comment by JakeWharton** [comment]
Like ActionBarSherlock I am now publishing this project to Maven central so I have to wait until Google updates the `frameworks/support.git` repository from AOSP. Only then can the new support library changes be deployed in a new artifact  to central. Once that is done updating this library will be a simple change.

For now, manual updating is the best way. I'll leave this open for others and as a reminder to me.

**Comment by rfgamaral** [comment]
Just curious, why do you publish your projects (the Android ones that I know of) to Maven Central? What's the purpose? Any advantages? Will it have any impact in the GitHub repo?

P.S: These may be stupid questions but I'm not even sure what Maven really is and I'm a little confused.

**Comment by JakeWharton** [comment]
Maven is a build framework but its bread and butter is easy and automated dependency management. Adding, removing, or updating a dependency is as easy as tweaking a line or two in the configuration file and the downloading and adding to your classpath is handled automatically. This becomes especially useful with library projects since it will automatically handle adding the resources to your project as well.

**Comment by markus2610** [comment]
You are using maven for eclipse or intellij idea?

**Comment by JakeWharton** [comment]
I use IDEA.

---

Jake Wharton
http://about.me/jakewharton

On Sun, Mar 25, 2012 at 12:04 AM, Markus <
reply@reply.github.com

**Comment by markus2610** [comment]
Run your Projcect with intellij idea, example debugging or only with maven.

**Comment by mr-thierry** [comment]
Is it possible to update this project with the latest support library, similarly to ActionBarSherlock?

**Comment by JakeWharton** [comment]
Fixed in `dev`
