### ISSUE TITLE
Spannable Title

### ISSUE THREAD

**Issue by JerryWard** [JakeWharton/ViewPagerIndicator#79]
It is possible to change the String getTitle() to CharSequence getTitle() and then change how the text is painted? It seems that the mPaint color variable when drawing the text to the canvas is the only missing link to allowing someone to return a Spannable String (that will be displayed with its styling) instead of a regular String without changing the ability to return regular Strings.

**Comment by JakeWharton** [comment]
We'll be changing to use [`PagerAdapter#getPageTitle`](http://developer.android.com/reference/android/support/v4/view/PagerAdapter.html#getPageTitle%28int%29) in the next version. So, yes!

**Comment by JerryWard** [comment]
Oh awesome, will look forward to that. I currently am using a hacked together version for changing the title text color, that involves calculating the color at I want the page I'm switching to to be, and changing the selected title to that color. Which ends up looking fine, but has a few small instances where what's going on in the code is revealed a little.

**Comment by imminent** [comment]
This issue doesn't seem to be resolved with the change to use `PagerAdapter#getPageTitle` because as I read it, `TitlePageIndicator` is calling `toString()` on the `CharSequence` in the return statement, which loses the spans as far as I know.
