### ISSUE TITLE
Problem when using linear layout weight and layout_width = 0

### ISSUE THREAD

**Issue by franciscojunior** [JakeWharton/ViewPagerIndicator#8]
Hi!

I was testing my app on honeycomb and I used a different layout as per the documentation to contain may master list on the left and my details fragment on the right.

The problem is that if I use the weight property to specify a percentage of the screen to be used by my master list, the titlepageindicator gives a error saying:

"ViewFlow can only be used in EXACTLY mode."  

btw, I think this error message should be changed too :)

The only possible ways I could make it work were:
1. specifying a hardcoded value for the width ( not ideal )
2. specifying the width as match_parent and specify a reversed value for the weight. I could get the layout the way I wanted, but it isn't using the documentation way of setting the width to 0 and specifying the weight value accordingly.

**Comment by JakeWharton** [comment]
Wrap the indicator in a `FrameLayout` (or any `ViewGroup`) and specify the percentage on that. Then use `fill_parent` on the indicator.

I'm not sure if the drawing can be done properly when the width isn't an exact amount. I'll have to look into it more. I'm going to close this for now though.
