### ISSUE TITLE
Publish built library jar as well as apklib on Maven Central

### ISSUE THREAD

**Issue by rtyley** [JakeWharton/ViewPagerIndicator#82]
IntelliJ has an issue with Android maven-based projects, in that it won't recognise classes from apklibs if you try to reference them in your code. A workaround for this is tweaking the dependencies of the project using the apklib, so that the apklib is also included as a dependency of type `jar` and scope `provided` - like we do with the ABS library [here](https://github.com/github/gauges-android/blob/9023302/app/pom.xml#L57-69):

```
    <dependency>
        <groupId>com.actionbarsherlock</groupId>
        <artifactId>library</artifactId>
        <version>${abs.version}</version>
        <type>apklib</type>
    </dependency>
    <dependency>
        <groupId>com.actionbarsherlock</groupId>
        <artifactId>library</artifactId>
        <version>${abs.version}</version>
        <type>jar</type>
        <scope>provided</scope>
    </dependency>
```

Unfortunately we're not able to do this hack with ViewPagerIndicator, because a built jar for ViewPagerIndicator isn't currently published to Maven Central... could you consider uploading one?

**Comment by rtyley** [comment]
Actually, [this comment](http://youtrack.jetbrains.com/issue/IDEA-82962#comment=27-321507) by Eugene Kudelevsky on IntelliJ may be of interest (also relates to issue #78)

**Comment by Eugene-Kudelevsky** [comment]
@rtyley I didn't know about such problem. Did you submit related issue to JetBrains's tracker?

**Comment by rtyley** [comment]
Ah, apologies @Eugene-Kudelevsky - there _wasn't_ a bug with IntelliJ IDEA, this behaviour ("not recognising classes from apklibs") was because we were using a forked version of the `android-maven-plugin`. Instead of:

```
<groupId>com.jayway.maven.plugins.android.generation2</groupId>
<artifactId>android-maven-plugin</artifactId>
<version>3.2.0</version>
```

...we were using the almost indistinguishable:

```
<groupId>com.madgag</groupId>
<artifactId>android-maven-plugin</artifactId>
<version>3.1.1.99.0.6</version>
```

This forked version of the `android-maven-plugin` added screenshot-taking capability, but crucially _was not_ recognised by IDEA - because the Jayway group id is (very reasonably) [hard-coded](http://git.jetbrains.org/?p=idea/community.git;a=blob;f=plugins/android/src/org/jetbrains/android/maven/AndroidFacetImporterBase.java;h=e4dd5f37e23f7e642ac6ad6c34649aaf078424d0;hb=10eac0023e7632e8b37c0212608ee8b7a46b3460#l76) into IDEA. So IDEA didn't import all the Android-facet data, leading to classes from apklib dependencies not being recognised.

The fork has been merged, so there's no longer any need to use it - sorry about the confusion.
