### ISSUE TITLE
GridLayout and ViewPagerIndicator

### ISSUE THREAD

**Issue by chrisjenx** [JakeWharton/ViewPagerIndicator#88]
The orientation attribute conflicts with the view pager indicator.

This can be fixed of course by removing the orientation definitions but a better fix is needed.

There also seems to be some conflict between gridlayout and abs but I can't seem to work that one out and i'll post in ABS for that.

**Comment by JakeWharton** [comment]
I'll switch it to use the build-in `android:orientation` attribute soon. Thanks for the report. I hate that custom attributes can clash like this.
