### ISSUE TITLE
Allow cyclic titles/tabs

### ISSUE THREAD

**Issue by rafael-munoz** [JakeWharton/ViewPagerIndicator#92]
Hi

Is there any way to have cyclic titles? In some use cases it would be fit better than the standard sequential panels.

Just to be clear, my idea is to have always a central title and a left and right one at its sides. Nicer user experience IMHO. 

Example:

 3 ->1 -> 2 -> 3 -> 1

**Comment by JakeWharton** [comment]
Non-cyclic behavior is a limitation of `ViewPager` and not this library. If `ViewPager` supported it then I certainly would be all for it here. If you want you can request something like this by filing an issue on http://b.android.com.
