### ISSUE TITLE
Crash when switching between higher level fragments

### ISSUE THREAD

**Issue by navarr** [JakeWharton/ViewPagerIndicator#93]
Right now for debug I have a TabPageIndicator with a ViewFragment that pulls five of the same fragment.  That fragment has on it a CirclePageIndicator with a ViewPager enclosed in a self-made view along with a TabPageIndicator and another ViewPager enclosed in a self-made view.

Switching from the first page -> second page -> first page works fine.
Switching from first page -> last page -> first page crashes.

So it probably has something to do with it leaving memory.  When it tries to load back in this happens:

05-10 17:05:44.361: E/AndroidRuntime(16954): FATAL EXCEPTION: main
05-10 17:05:44.361: E/AndroidRuntime(16954): java.lang.ClassCastException: android.view.AbsSavedState$1 cannot be cast to com.viewpagerindicator.CirclePageIndicator$SavedState
05-10 17:05:44.361: E/AndroidRuntime(16954):    at com.viewpagerindicator.CirclePageIndicator.onRestoreInstanceState(CirclePageIndicator.java:514)
05-10 17:05:44.361: E/AndroidRuntime(16954):    at android.view.View.dispatchRestoreInstanceState(View.java:9876)
05-10 17:05:44.361: E/AndroidRuntime(16954):    at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2330)
05-10 17:05:44.361: E/AndroidRuntime(16954):    at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2330)
05-10 17:05:44.361: E/AndroidRuntime(16954):    at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2330)
05-10 17:05:44.361: E/AndroidRuntime(16954):    at android.view.View.restoreHierarchyState(View.java:9854)
05-10 17:05:44.361: E/AndroidRuntime(16954):    at android.support.v4.app.Fragment.restoreViewState(Fragment.java:407)
05-10 17:05:44.361: E/AndroidRuntime(16954):    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:897)
05-10 17:05:44.361: E/AndroidRuntime(16954):    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1080)
05-10 17:05:44.361: E/AndroidRuntime(16954):    at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:622)
05-10 17:05:44.361: E/AndroidRuntime(16954):    at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1416)
05-10 17:05:44.361: E/AndroidRuntime(16954):    at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:431)
05-10 17:05:44.361: E/AndroidRuntime(16954):    at android.support.v4.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:160)
05-10 17:05:44.361: E/AndroidRuntime(16954):    at android.support.v4.view.ViewPager.populate(ViewPager.java:804)
05-10 17:05:44.361: E/AndroidRuntime(16954):    at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:433)
05-10 17:05:44.361: E/AndroidRuntime(16954):    at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:405)
05-10 17:05:44.361: E/AndroidRuntime(16954):    at android.support.v4.view.ViewPager.setCurrentItem(ViewPager.java:386)
05-10 17:05:44.361: E/AndroidRuntime(16954):    at com.viewpagerindicator.TabPageIndicator$1.onClick(TabPageIndicator.java:41)
05-10 17:05:44.361: E/AndroidRuntime(16954):    at android.view.View.performClick(View.java:3480)
05-10 17:05:44.361: E/AndroidRuntime(16954):    at android.view.View$PerformClick.run(View.java:13983)
05-10 17:05:44.361: E/AndroidRuntime(16954):    at android.os.Handler.handleCallback(Handler.java:605)
05-10 17:05:44.361: E/AndroidRuntime(16954):    at android.os.Handler.dispatchMessage(Handler.java:92)
05-10 17:05:44.361: E/AndroidRuntime(16954):    at android.os.Looper.loop(Looper.java:137)
05-10 17:05:44.361: E/AndroidRuntime(16954):    at android.app.ActivityThread.main(ActivityThread.java:4340)
05-10 17:05:44.361: E/AndroidRuntime(16954):    at java.lang.reflect.Method.invokeNative(Native Method)
05-10 17:05:44.361: E/AndroidRuntime(16954):    at java.lang.reflect.Method.invoke(Method.java:511)
05-10 17:05:44.361: E/AndroidRuntime(16954):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
05-10 17:05:44.361: E/AndroidRuntime(16954):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
05-10 17:05:44.361: E/AndroidRuntime(16954):    at dalvik.system.NativeStart.main(Native Method)

**Comment by SimonVT** [comment]
This doesn't seem to be caused by ViewPagerIndicator, but rather by the framework passing in the wrong state.
From what I understand, you have a Fragment with a UI in a Fragment with a UI. That is currently not supported by the Fragment API, and is probably why it's breaking.

**Comment by navarr** [comment]
No, no.  Just one fragment.  Everything else are just views.

**Comment by SimonVT** [comment]
Can you make a sample project which exhibits this behavior?

**Comment by navarr** [comment]
## I'll try.

Navarr T. Barnier
navarr@gtaero.net
http://navarr.me/

On Fri, May 11, 2012 at 6:43 AM, SimonVT
reply@reply.github.com
wrote:

**Comment by navarr** [comment]
A zip containing an example project is available at https://docs.google.com/open?id=0BwbUoWpkXDCGR2pDM1JiZnlFMjg

If you run the app and go from First (default) to Fifth and then back to First the app will crash with the above exception.

**Comment by navarr** [comment]
Note: Using ABS v4.0.2 with ViewPagerIndicator 2.2.3

**Comment by SimonVT** [comment]
Yeah, not caused by VPI. If you give each indicator/pager a unique id, there's no issue.

**Comment by navarr** [comment]
Oh.  My apologies.
