### ISSUE TITLE
Multiple TabPagerIndicators with multiple styles

### ISSUE THREAD

**Issue by navarr** [JakeWharton/ViewPagerIndicator#94]
I have a couple of TabPagerIndicators that are in the same activity that I want to style differently.  However, I can't seem to apply inline styles to them (probably because the actual widget pulls from ?attr).

If there is a proper way to do this, then I'm asking for help (I searched a bit for a forum to do so but didnt find it here nor on the site) and if there isn't than I guess this is a feature request?

**Comment by SimonVT** [comment]
Have you tried setting the style tag in xml, or passing the style in the constructor?

**Comment by navarr** [comment]
I have not tried passing the style in the constructor.  Maybe I didn't look hard enough but I didn't find an example of it.

Setting the style tag in XML ends up with extra padding in the LinearLayout, but none of the other styles seem to apply.  (In my case I'm using a different drawable for the background states), and the sample here only seems to show it through a theme.

**Comment by SimonVT** [comment]
Ah, you're having issues with vpiTabTextStyle ? Yeah, not sure you can set separate styles for multiple indicators in the same activity from xml.
You'll probably have to do it all from code, passing the indicators a http://developer.android.com/reference/android/view/ContextThemeWrapper.html with your different styles.

**Comment by JakeWharton** [comment]
While a super-rare case, an attempt to support this should still be made. I know a lot more about Android styling than I did back when this project was started so it should be a trivial fix.

**Comment by navarr** [comment]
@SimonVT While trying out that as a workaround by stuffing it into its own class that I'm using.. it works well in that I can see the new style taking affect - but it's ALSO applying the old style.  Which is _really_ weird.

![Example Image](http://i.imgur.com/R1ECC.png)

I'm probably doing something very wrong here.  The bar on the top is the new style, which I've applied in the code inc. below:

``` java
public class TopTabPageIndicator extends TabPageIndicator {
    public TopTabPageIndicator(Context context)
    {
        this(context,null);
    }
    public TopTabPageIndicator(Context context, AttributeSet attrs) {
        super(new ContextThemeWrapper(context,R.style.Widget_Bgsu_TabPageTopIndicator), attrs);
    }
}
```

**Comment by SimonVT** [comment]
I think you might have to pass it a theme that extends from e.g. android:Theme, and defines both attributes related to TabPageIndicator.

**Comment by navarr** [comment]
OH!  As in an entire theme, yeah, that would be my mistake.

That did the trick.  Thanks a bunch, @SimonVT!

With the amount of awesome projects @JakeWharton is producing, he could probably get away with starting a company that offers support for them :p

**Comment by murthyanitaa** [comment]
Hi, can you please tell me how to solve this? Facing the same issue..

**Comment by murthyanitaa** [comment]
"I think you might have to pass it a theme that extends from e.g. android:Theme, and defines both attributes related to TabPageIndicator." Can you please guide me on how to achieve this? Thanks a lot!

**Comment by murthyanitaa** [comment]
Hi I seem to be having the exact same issue here. Can you please help me??!!!!
