### ISSUE TITLE
Can't import library to eclipse

### ISSUE THREAD

**Issue by sebastiandeutsch** [JakeWharton/ViewPagerIndicator#96]
Hi,

I've cloned the repository and tried to import the library folder, but unfortunately eclipse tells me that there is no project to import:

```
"No projects are found to import"
```

I also tried to create a new Android Project at the library source, but then the src and res folder are empty. Could you give me a hint how to include that component?

Best

Sebastian

Eclipse: Helios Service Release 2
ADT: 17.0.0.v201203161636-291853

**Comment by JakeWharton** [comment]
An Eclipse project is not included. If you want to use Eclipse with the library you will need to create a new Android project, selected "from existing sources", and choose the 'library' folder in the prompt.

If you are experiencing problems importing using the above technique then it's a bug in either Eclipse or the ADT Eclipse Plugin. [This filed bug](http://code.google.com/p/android/issues/detail?id=8431) might be related.

**Comment by sebastiandeutsch** [comment]
Yes, it's probably a bug in eclipse. I created an Android project from source (library folder) - but then some files were missing. The trick was to import the files a second time (Import -> Files from filesystem -> Overwrite existing files). Maybe this helps if another person is asking.
